### ISSUE TITLE
Where do we add packages like "vim" and "nano"?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cloud-federation#11]
I could not figure out how to get system packages like "vim" and "nano" into the notebook environment.

**Comment by jhamman** [comment]
You'll want to these to the postBuild script. Something like `sudo apt-get install vim` is all you need.

**Comment by mrocklin** [comment]
The binder directory follows the specs for
https://repo2docker.readthedocs.io/en/latest/

See the section "Complete list of configuration files"

It includes apt.txt

**Comment by jhamman** [comment]
Yes, or you can put them in the apt.txt config file (not presently in the repo). @mrocklin's idea is probably better.

**Comment by rsignell-usgs** [comment]
Awesome.  Thanks guys!   I'll try out `app.txt`.
