### ISSUE TITLE
aws authentication 

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#112]
@apawloski, @scottyhq, and I have been working on getting this repo setup with a new `nasa` deployment running on AWS. We've been making some changes to hubploy in https://github.com/yuvipanda/hubploy/pull/14 and have added most of the necessary bits to this repo. 

We're currently stuck getting the eks authentication to work. This could just be how we've setup the IAM account but I'm posting here to coordinate the final pieces. The current error is:

```
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Error: Get https://958CB6CD107C87EEDAA83BFFEE9EEAFA.sk1.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: getting credentials: exec: exit status 1
```

The command `aws eks update-kubeconfig --name pangeo` succeeds but is not giving us sufficient privileges. I'm hoping @apawloski knows what to do here.

**Comment by apawloski** [comment]
At which point do you get the error? This means that whatever AWS utility you're using doesn't see your credentials file. (It expects it to be in `~/.aws/credentials` -- elsewhere we've been using the `$AWS_SHARED_CREDENTIALS_FILE` env var to point to it.)

**Comment by scottyhq** [comment]
This is subtle, but after some local experimenting with https://github.com/awslabs/amazon-ecr-credential-helper: `secrets/creds.txt` (pointed to by `AWS_SHARED_CREDENTIALS_FILE`)  **only reads the access keys, not the region or other configuration settings** 
(https://docs.aws.amazon.com/cli/latest/topic/config-vars.html)

so I think we have to set `--region` explicitly and make sure that environment variable is being read as andrew suggested. this issue about restarting docker to find the right path might also be relevant: https://github.com/awslabs/amazon-ecr-credential-helper/issues/49#issuecomment-338963701

**Comment by scottyhq** [comment]
it seems like the easiest solution is just putting the credentials in the standard place, that way the various commands depending on them will locate them without the need for environment variables? @yuvipanda , can we just do `shutil.copyfile(service_key_path, ~/.aws/credentials)`? 

The the following works locally after adding the circleci user permissions to the cluster (see https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html)

```bash
(hubploy) scott@pangeo-cloud-federation:AWS_SHARED_CREDENTIALS_FILE=/Users/scott/.aws/aws-config.txt aws eks update-kubeconfig --name pangeo
Updated context arn:aws:eks:us-east-1:783380859522:cluster/pangeo in /Users/scott/.kube/config
(hubploy) scott@pangeo-cloud-federation:kubectl get svc
error: the server doesn't have a resource type "svc"


(hubploy) scott@pangeo-cloud-federation:docker pull 783380859522.dkr.ecr.us-east-1.amazonaws.com/pangeo:latest
ERRO[0000] Error retrieving credentials                  error="ecr: Failed to get authorization token: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
Error response from daemon: Get https://783380859522.dkr.ecr.us-east-1.amazonaws.com/v2/pangeo/manifests/latest: no basic auth credentials
```

Things work after moving the credentials file (the error from docker is because there is no image yet in that ecr repo, not a permissions error): `cp /Users/scott/.aws/aws-config.txt ~/.aws/credentials`:

```
(hubploy) scott@pangeo-cloud-federation: docker pull 783380859522.dkr.ecr.us-east-1.amazonaws.com/pangeo:latest
Error response from daemon: manifest for 783380859522.dkr.ecr.us-east-1.amazonaws.com/pangeo:latest not found

NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   11d
```
```

**Comment by yuvipanda** [comment]
@scottyhq yeah, let's do that for now. That's sortof what happens with Google Cloud, so I'm ok with it.

**Comment by scottyhq** [comment]
alright! authentication is working! but we have a new error, seems that we had tiller version 2.11 installed on our EKS cluster, but the google deployments were using 2.12. currently we install helm 2.12 in circleci, so I upgraded tiller more or less following zero2jhub docs:
https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-helm.html 

```
curl -O https://storage.googleapis.com/kubernetes-helm/helm-v2.12.0-darwin-amd64.tar.gz
 tar -xzf helm-v2.12.0-linux-amd64.tar.gz
./darwin-amd64/helm init --service-account tiller --wait --upgrade

**Comment by scottyhq** [comment]
Once https://github.com/yuvipanda/hubploy/pull/16 is merged we can switch back to using yuvi's master branch:
https://github.com/pangeo-data/pangeo-cloud-federation/blob/48c818996a5a7383a94b76e52effa30d08ccf199/requirements.txt#L1
