### ISSUE TITLE
move nfs configuration to deployments instead of under pangeo-deploy

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#122]
we're running into an issue with `helm upgrade` for deploying to aws that is related to nfs configuration settings under the shared `pangeo-deploy` directory. This is resolved by deleting these settings, but doing so will presumably affect GCS deployments:
https://github.com/scottyhq/pangeo-cloud-federation/commit/6dd4f1871fcef26c0d4cdfa2b8e3be5fbcddda64

Should we ensure whatever is under pangeo-deploy is as bare-bones as possible and not linked to specific cloud providers or deployments?

```
helm upgrade --wait --install --namespace nasa-staging nasa-staging pangeo-deploy -f deployments/nasa/config/common.yaml -f deployments/nasa/config/staging.yaml -f deployments/nasa/secrets/staging.yaml --set jupyterhub.singleuser.image.tag=a7ff12a --set jupyterhub.singleuser.image.name=pangeo/nasa-pangeo-io-not
```

```
Error: release nasa-staging failed: PersistentVolume "nasa-staging-home-nfs" is invalid: spec.nfs.server: Required value
```

**Comment by yuvipanda** [comment]
Yep, I agree!

1. wrap https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/pangeo-deploy/templates/home-storage.yaml with '{{ if .Values.homeDirectories.nfs.enabled }}'
2. Set 'homeDirectories.nfs.enabled' to false in https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/pangeo-deploy/values.yaml#L38, and move the current contents there to the deployment directories

The NFS stuff isn't cloud provider specific though - I think EFS will work pretty much exactly the same, with just different ip and server name values.
