### ISSUE TITLE
use jupyterhub latest master (>0.9.4)

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#136]
In order to make my custom logo work on ocean.pangeo.io., I need a jupyterhub with [this](https://github.com/jupyterhub/jupyterhub/pull/2296) PR in it. The latest release of jupyterhub was in September, 0.9.4, and does not include that PR.

We currently point to jupyterhub help chart version `0.9-e120fda`. I assumed that would be pulling in a very recent master, since it is a devel release tagged on March 1. (https://jupyterhub.github.io/helm-chart/) But apparently this is not the case. I believe our hubs are using 0.9.4.

**Comment by jhamman** [comment]
this is now being done via the pangeo chart (closed by #90)

**Comment by rabernat** [comment]
This issue is not actually fixed. Whether we point to the pangeo or jupyterhub chart, we are still ultimately relying on jupyterhub chart `0.9-e120fda`. The version of jupyterhub installed by this chart is apparently 0.9.4, not the latest master.

The way I know this is that I ssh in to the pod (`kubectl -n ocean-staging exec -it hub-7b57498dd9-qzzsk -- /bin/bash`) and examine the file `/usr/local/share/jupyterhub/templates/page.html`. It is different from https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyterhub/templates/page.html (doesn't have a `logo` block.)

This is not a big deal and will likely be resolved when jupyterhub 1.0.0 is released.
