### ISSUE TITLE
ocean staging notebooks won't launch

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#161]
I had a notebook pod die spontaneously. Now I can't start any more.

```
2019-03-24 02:47:40+00:00 [Warning] 0/11 nodes are available: 1 node(s) had disk pressure, 10 Insufficient memory, 2 Insufficient cpu.
2019-03-24 02:47:48+00:00 [Normal] pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

One possible related point is that I was downloading O(5 GB) of data to the /tmp directory. I _thought_ that this was sitting on a 100 GB SSD. But it might be that I filled up some disk somewhere.

It's weird that the node pools won't just scale up to accommodate a new pod.

**Comment by rabernat** [comment]
In trying to fix this, I managed to make things much worse.

I did the very dumb thing of trying to resize the default pool down to size 0 to kill the messed up nodes.

This operation is stuck in a pending state. As long as it can't complete, I can't try anything else. In the meantime, key pods like autohttps can't get scheduled.

**Comment by rabernat** [comment]
So the pending state is resolved and the cluster is superficially back to normal.

However, I am still seeing these errors:

```
2019-03-24 13:38:44+00:00 [Warning] 0/2 nodes are available: 2 Insufficient cpu, 2 Insufficient memory.
2019-03-24 13:39:00+00:00 [Normal] pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

I the n1-standard-highmem node pool _should_ be able to scale up to fit these pods, but for some reason this is not happening.

**Comment by rabernat** [comment]
Latest update: I manually scaled the n1-standard-highmem up to size 1, and my notebook finally launched again.

So why would it not scale up on its own?

**Comment by rabernat** [comment]
Ok, now the node pool seems to be scaling normally.

**Comment by jhamman** [comment]
@rabernat - okay to close?
