### ISSUE TITLE
Is the dask dashboard working as intended?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cloud-federation#18]
Are we supposed to manually drop the dashboard URL into JupyterLab, or is this supposed to happen automagically?

![2018-10-31_8-31-53](https://user-images.githubusercontent.com/1872600/47810135-e7a36980-dd18-11e8-9e16-66742081c650.png)

**Comment by jhamman** [comment]
@rsignell-usgs - I think there are two ways this can work:

1. Manually copy the dashboard URL
2. Using the jupyterlab workspace extension that @@ian-r-rose built, you can have this automagically updated. This currently uses a default URL set on login (via the start script).

**Comment by mrocklin** [comment]
So we magically populate this today by using sed when the image starts up.
I recommend referring to the solution in github.com/dask/dask-examples

**Comment by ian-r-rose** [comment]
In addition to what @jhamman and @mrocklin said, clicking on the "Search" icon attempts to automatically pick up the dashboard URL from the active notebook kernel. It's not 100%, though.

**Comment by rsignell-usgs** [comment]
@mrocklin , this is it, right?
https://github.com/dask/dask-examples/commit/1ed945162f544b6df821e2b18750ec0a082c01aa

**Comment by ian-r-rose** [comment]
Yes
