### ISSUE TITLE
move staging to production deployments

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#190]
We'd like to start moving `staging.[deployment].pangeo.io` to production deployments. What needs to happen to do this? 

* for starters, it seems like we should get back to using @yuvipanda 's hubploy: https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/requirements.txt 

what else?

**Comment by jhamman** [comment]
I think we can do this pretty quickly. We need to make sure a few things are in place though.

- [x] each cluster has the prod.yaml files in place (@rabernat and @raphaeldussin - ocean is missing this, @bartnijssen - hydro is missing this)
- [x] our k8s cluster can accommodate additional hubs (I can scale up the gcp cluster for ocean/dev/hydro)

Once those tasks are done, we need to go through the standard process of updating the dns/https/etc.

**Comment by jhamman** [comment]
The following hubs are now live:
- hydro.pangeo.io
- ocean2.pangeo.io (we can rename this hub when @rabernat and @raphaeldussin are ready)
- hub.pangeo.io (prod of dev deployment)
- icesat2.pangeo.io

We still need to add auth to most of these hubs.

**Comment by yuvipanda** [comment]
Where is this at now?

**Comment by jhamman** [comment]
This can be closed. @rabernat and @raphaeldussin are making progress on ocean.pangeo.io but don't need this issue to do so.
