### ISSUE TITLE
Replace readme?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cloud-federation#2]
Should we replace the generic readme with something that explains this setup?

| Branch | Deployed at |
| -------  | ------------   |
| develop | https://dev.pangeo.io |
| staging | https://staging.pangeo.io |
| prod | https://hub.pangeo.io |

and perhaps something about the process and how long it takes changes in the `environment.yml` or other config to take effect?

**Comment by mrocklin** [comment]
Yes

**Comment by rsignell-usgs** [comment]
Thanks @dsludwig!
