### ISSUE TITLE
Use Google Cloud Filestore for shared storage

### ISSUE THREAD

**Issue by yuvipanda** [pangeo-data/pangeo-cloud-federation#25]
Google Cloud now has a managed NFS provider ([Filestore](https://cloud.google.com/filestore/)) that would be great for home directories. Currently, each user gets their own disk, which is expensive and rigid (you can't easily change sizes up or down after creation). It also makes some sharing scenarios harder.

Steps to use filestore:

1. Create a filestore 
2. Configure z2jh to use NFS as the backing store for home directories. We use one filestore for all users, and use `subPath` to give them rw access to each directory. This is used to scope users to directories, rather than traditional Unix user permissions
3. Use an initContainer to make sure the home directory created for the user has right permissions and ownership. See https://serverfault.com/questions/906083/how-to-mount-volume-with-specific-uid-in-kubernetes-pod for example.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/amazon/efs_storage.rst is some info on doing something like this with EFS, which is used on AWS. Step (3) would be different. 

Once we have a good idea on how to set this up, this can be contributed back to the z2jh docs.

**Comment by rabernat** [comment]
@raphaeldussin - we definitely want this for ocean.pangeo.io

**Comment by yuvipanda** [comment]
Step 1: Convert default pool to use ubuntu for nodes, rather than default container optimized os. Ubuntu comes with ability to use NFS, this does not. I did this in the GUI in two steps:

1. Hit edit in the Kubernetes cluster page
2. Edit the nodepool
3. Turn 'node autorepair' to 'off'
4. Save

1. Hit edit in the Kubernetes cluster page
2. Edit the nodepool
3. Change 'node image' to ubuntu
4. Save

Progress is in the 'notifications' icon in top right. It takes a while and deletes / recreates all nodes. This disrupts all pods on the nodepool.

You can also specify this while creating the cluster.

**Comment by yuvipanda** [comment]
Turns out this was a bad idea because of poddisruptionpolicy that is set by JupyterHub. I'm working around this manually just now, but in the future, the thing to do is to create a *new* nodepool with Ubuntu and kill the old nodepool after the new one is up.

**Comment by yuvipanda** [comment]
This has been sorted out now. I'll continue tomorrow!

**Comment by yuvipanda** [comment]
#28 is all the config required to make this happen. Woohoo!

I created the filestore instance with:

```
gcloud beta filestore instances create --file-share=name=test,capacity=1TiB  --location=us-central1-b --network=name=default dev-home
```

**Comment by yuvipanda** [comment]
This also lets you share home directories between dask workers and user notebooks. You'd need to convert the dask workers pool to Ubuntu node images first, but otherwise it's a matter of setting up appropriate volume and volumeMount fields in the dask pod specification.

**Comment by rabernat** [comment]
This is fantastic Yuvi! This is a major improvement to the way we are handling user storage.

Do any tools exist for monitoring the shared filesystem? Is there an easy way to see how much space the different users are using? Or enforce quotas?

**Comment by yuvipanda** [comment]
@rabernat glad to be of use! Unfortunately, there is no easy way to systematically see how much users are using or to enforce quotas. You can run the 'du -h' command on the root of the filesystem maybe, but there isn't an easy way to do that yet.

**Comment by mrocklin** [comment]
Do normal filesystem quotas work here by any chance?

**Comment by yuvipanda** [comment]
@mrocklin XFS is the only filesystem I know of that does quotas, and IIRC those are per user. We don't have individual Unix users, and we don't control the filesystem in the mount here (Google does). So I don't think they work

**Comment by jhamman** [comment]
@yuvipanda - what happens when one uses, say jhamman, logs onto multiple jupyterhubs that share the same filesystem. Is it safe to assume jhamman will get the same home directory in each hub? Are there any potential conflicts there?

**Comment by dsludwig** [comment]
Should we prefix the home directories with the name of the deployment/cluster? I could foresee issues with clobbering the `.dask/config.yaml` or `binder/*` contents.

Maybe the right way to deal with that is to move some of those out of the mounted directory, rather than not sharing home directories.

**Comment by mrocklin** [comment]
For Dask config files we can place "system" (in this case docker image or
whatever) config files in /etc/dask and let the user have their own config
files in their home directories.
http://docs.dask.org/en/latest/configuration.html

**Comment by yuvipanda** [comment]
On the filestore, I agree we should prefix them with hub name - or whatever we want the unit of 'home directory' to be. I personally isolate them per-hub, but that might not make sense for you.

**Comment by yuvipanda** [comment]
+1 for putting stuff that can't be moved into /etc/dask and letting user overrides in $HOME.

**Comment by mrocklin** [comment]
During today's call @rabernat suggested that there might be some value to
having a shared home among different deployments.

**Comment by consideRatio** [comment]
Thank you for this @yuvipanda! I'll try this out very soon i think.
