### ISSUE TITLE
Deployment secrets for AWS?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cloud-federation#263]
The doc says:
> Configure the deployment secrets found in deployments/foobar/config.
> gcloud-service-key.json: a service account key for gcloud. This is slightly different when AWS.

So where could I find this slightly different info for AWS?  
(I don't see it here: https://github.com/pangeo-data/ACCESS_K8S)

**Comment by jhamman** [comment]
@scottyhq and @amanda-tan are the likely authorities on the AWS auth stuff at the moment.

@rsignell-usgs - before you get started here, it will be useful for you to get a Keybase account if you don't already have one.

**Comment by scottyhq** [comment]
Note that if you are deploying to the same AWS account you don't need new deployment keys. The encrypted keys are the the access keys for our 'circleci' iam user:

```
[circleci]
aws_access_key_id=XXXXXXX
aws_secret_access_key=XXXXX
```

@rsignell-usgs - are you redeploying on an ESIP account?

**Comment by rsignell-usgs** [comment]
@scottyhq and @jhamman, no I'm trying to deploy on the EKS kube cluster that USGS set up for me.

**Comment by jhamman** [comment]
@rsignell-usgs - did you get this sorted?

**Comment by rsignell-usgs** [comment]
Yes, okay to close

-Rich
