### ISSUE TITLE
Trying to save data as a NetCDF file by Xarray. Got the error 'FileNotFoundError: No such file or directory'

### ISSUE THREAD

**Issue by liutongya** [pangeo-data/pangeo-cloud-federation#277]
I'd like to save the SLA in a small region from the satellite as a NetCDF file, but it doesn’t work. The error signs “FileNotFoundError: [Errno 2] No such file or directory: 

This could be reproduced by:

`import numpy as np`
`import xarray as xr`
`import gcsfs`
`gcsmap = gcsfs.mapping.GCSMap('pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt')`
`ds = xr.open_zarr(gcsmap)`
`sla = ds.sel(longitude=slice(100,130),latitude=slice(0,30),time=slice('2012-02-01')).sla`
`sla.to_netcdf('test')`

This data-saving could be done successfully in the old Pangeo. We have tried with both Xarray 0.12.0 and 0.11.0, but it still showed the same error.

**Comment by rabernat** [comment]
@liutongya I would make sure you call `.load()` before you call `.to_netcdf()` to make sure you are not trying to use dask to write.

**Comment by liutongya** [comment]
It works if I call `.load()` first. Thanks.
