### ISSUE TITLE
ocean-prod is broken: hub unschedulable

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#291]
I made an enourmous dask cluster on ocean-prod. (100 workers with 8 threads each). It worked okay on the backend, but it crashed something elsewhere in the backend. My current theory is that it might have overwhelmed the hub proxy with all the info it was sending through the dashboard.

In any case, the hub crashed and won't come back up. Its pod status is "pending". In the dashboard, I see the following info.

PodUnschedulable
Cannot schedule pods: Insufficient cpu.
PodUnschedulable
Cannot schedule pods: Insufficient memory.
PodUnschedulable
Cannot schedule pods: node(s) didn't match node selector.

I fear this involves @jhamman's new node affinity magic. I have tried killing the pod, but it just returns to pending status.

I have no idea how to debug this. So I have broken a production cluster. Urgently requesting some help to fix it asap! 😱

**Comment by rabernat** [comment]
So I resolved this by resizing the core pool from 3 to 4 nodes. Seems obvious in retrospect. But why is this necessary?

**Comment by TomAugspurger** [comment]
I may be wrong, but I think that message like

```
PodUnschedulable
Cannot schedule pods: Insufficient cpu.
...
```

are normal when a pod could be put in a node pool, but the taint / affinity doesn't allow it. Then autoscaling of the node pool should be triggered, and the pod will be scheduled when the node pool has resized. I'm trying to check the logs now, but I think my gcloud permissions are a bit wonky right now.

**Comment by rabernat** [comment]
So this hub pod wants to live in the "core-pool", which is not autoscaling. I think what happened is that the hub pod crashed, some other pod (maybe from a different cluster) moved into the core-pool, and now the core-pool didn't have any more room once the new hub pod wanted to come back up.
