### ISSUE TITLE
Is CI properly updating the deployment?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cloud-federation#3]
It looks like the PR worked it's way through CI successfully: https://circleci.com/gh/pangeo-data/dev.pangeo.io-deploy/14
but is there something I need to do additionally or differently?
When I start my server on dev.pangeo.io I just see the same old pre-PR environment -- it doesn't seem to be updated.

**Comment by mrocklin** [comment]
cc @dsludwig (also, can I ask you to watch this repository for the near future?)

**Comment by dsludwig** [comment]
It looks like it to me, I'm getting the new environment. You may have to shutdown and restart your jupyter server from here: https://dev.pangeo.io/hub/home

**Comment by rsignell-usgs** [comment]
@dsludwig indeed, I'm getting the new environment now.     
I must have just jumped the gun when I restarted before!

**Comment by mrocklin** [comment]
I'm very glad to see this working :)
