### ISSUE TITLE
paste into terminal vi session problem

### ISSUE THREAD

**Issue by robfatland** [pangeo-data/pangeo-cloud-federation#304]
I am using a Surface laptop. From the nasa.pangeo.io JHub I open a terminal and start editing using `vi`. I want to paste a bunch of text that I grabbed from elsewhere. ctrl+v does not work. But much worse: If I use ctrl+shift+v it hangs the entire Jupyter session forever until the heat death of the universe. Unless Scott clobbers it. 

Please note: ctrl+shift+v does work to paste text directly into the terminal command line, i.e. not in `vi`. So that's why I was trying to use it in `vi`. But don't do that. 

Best remedy: No drama, ctrl+v just works normally in all situations.

**Comment by rabernat** [comment]
@robfatland - thanks for reporting this problem.

This sounds like an issue with jupyterhub, and not our cloud-based deployment setup. I encourage you to open your issue there: https://github.com/jupyterhub/jupyterhub/issues. I'm sure they will be very receptive to helping resolve the problem.
