### ISSUE TITLE
ocean.pangeo.io spawning 16 cores

### ISSUE THREAD

**Issue by cpatrizio88** [pangeo-data/pangeo-cloud-federation#336]
Hello,

I have been using ocean.pangeo.io to do some analysis, however I fail to connect to server whenever I try to spawn an XL job (16 cores). The L job (8 cores) always works. Are these resources not available or have I just been unlucky so far?

Thank you!

**Comment by jhamman** [comment]
Hi @cpatrizio88 - these resources are not available in our cluster right now. Are you able to use dask-kubernetes workers in to scale out your analysis?

**Comment by cpatrizio88** [comment]
Hi @jhamman - thanks for the suggestion! For some reason I thought I would not be able to do that, but I just tried it out and it works very nicely. Thanks again!

**Comment by cpatrizio88** [comment]
@jhamman I spoke a little bit too soon... I can successfully create a dask-kubernete node with a number of workers (e.g. 10), but it appears that if I load more than 50 GB of data into memory my server crashes. The 10 workers alone should be able to support 230 GB of memory. Do you have any idea why this is happening?

**Comment by cpatrizio88** [comment]
It looks like my data is being stored in the system memory, as opposed to by the dask-kubernetes workers. For example, if x is some array, then x.persist() loads the array into system memory. The crash occurs because the system memory has a 50GB limit (for 8 cores).

Shouldn't data be loaded into memory of the dask-kubernetes workers?

**Comment by TomAugspurger** [comment]
Have you made a KubeCluster and connected a Client?

**Comment by cpatrizio88** [comment]
@TomAugspurger yes I use the following code

```
from dask.distributed import Client, progress
from dask_kubernetes import KubeCluster
cluster = KubeCluster(n_workers=20)
client = Client(cluster)
client
x = da.random.random((50000,50000), chunks=(2000,2000))
x.persist()
```

Here, x is a 20GB array. When I check the memory load on my dask workers it is near zero, but system memory is around 20GB:
<img width="845" alt="Screen Shot 2019-07-27 at 4 18 18 PM" src="https://user-images.githubusercontent.com/1316945/62000001-8da6b900-b08a-11e9-9d3b-ef8189467a0c.png">
<img width="690" alt="Screen Shot 2019-07-27 at 4 18 31 PM" src="https://user-images.githubusercontent.com/1316945/62000000-8da6b900-b08a-11e9-97d4-f8bbe7e57292.png">

**Comment by cpatrizio88** [comment]
OK, it looks like my config.yaml file was not set up properly (actually, it wasn't specified at all). 

As a fix, I copied the config.yaml file from pangeo-data/pangeo-example-notebooks/.dask/ and put it in my .config directory. That seemed to do the trick!
