### ISSUE TITLE
ocean.pangeo.io timing out

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#360]
Staging looks fine. Figuring out what's going on with https://ocean.pangeo.io now.

**Comment by TomAugspurger** [comment]
Lots of active dask worker pods right now. But the hub isn't working

```
 hub

 
Pod errors: Unschedulable
Show Details
 
Does not have minimum availability
Show Details
```

**Comment by TomAugspurger** [comment]
`kubectl -n ocean-prod describe pods hub-85469f86b6-ffpm6 `


```
Events:
  Type     Reason             Age                From                Message
  ----     ------             ----               ----                -------
  Warning  FailedScheduling   7m (x97 over 1h)   default-scheduler   0/75 nodes are available: 3 Insufficient cpu, 70 Insufficient memory, 72 node(s) didn't match node selector.
  Warning  FailedScheduling   2m                 default-scheduler   0/74 nodes are available: 3 Insufficient cpu, 69 Insufficient memory, 71 node(s) didn't match node selector.
  Normal   NotTriggerScaleUp  2m (x538 over 1h)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 3 node(s) didn't match node selector
```

**Comment by TomAugspurger** [comment]
@jhamman @rabernat do you know why autoscaling isn't enabled for the `core-pool`?

`$ gcloud container node-pools describe --cluster dev-pangeo-io-cluster core-pool `

**Comment by TomAugspurger** [comment]
I guess it's somewhat surprising that a large workload would overwhelm the core-pool, right @jhamman? From https://medium.com/pangeo/pangeo-cloud-cluster-design-9d58a1bf1ad3

> Core-pool: This is where we run things like the JupyterHub and other persistent system services (web proxies, etc.). We keep this as small as possible, just big enough to run core services.

I wonder how we can find out which component isn't scaling well.

**Comment by TomAugspurger** [comment]
OK, now that the cluster is less active, the `hub` has had a chance to be scheduled. It'd be nice to know

1. Why it went down in the first place (requiring a new `hub` pod to be deployed)
2. Whether we can auto-scale the `core` node pool for this situation

**Comment by jhamman** [comment]
In the last few minutes, I've done the following actions:

- killed all running dask processes in the ocean-prod namespace
- killed a few notebooks sessions that had been active for a long time
- increased the fixed size of the core pool to 4 nodes (up from 3)

>Why it went down in the first place (requiring a new hub pod to be deployed)

Agreed. My guess is that it went down randomly (perhaps the whole node went down) and other services took its spot before it could scale up. I think someone could do some investigative reporting on this if they are interested. 

>Whether we can auto-scale the core node pool for this situation

We can make the core-pool autoscaling but we'll need to work on the taints for the hub/scheduler/proxy pods. I personally find it easier to make this pool's size static and to let the other pools autoscale.

**Comment by TomAugspurger** [comment]
Thanks Joe. I don't think I'll have time near-term to investigate why the `hub` pod went away in the first place, so I'll close this now.

**Comment by rsignell-usgs** [comment]
I'm back from a week of vacation, and both `staging.esip.pangeo.io` and `esip.pangeo.io` are failing to start with:
![2019-08-12_16-55-00](https://user-images.githubusercontent.com/1872600/62897866-1d529580-bd22-11e9-9fa4-efabf2b8d128.png)

Should I leave it in this state for examination or start trying to fix?
