### ISSUE TITLE
How would this differ for an AWS deployment?

### ISSUE THREAD

**Issue by apawloski** [pangeo-data/pangeo-cloud-federation#37]
While most of this should be cloud agnostic (because it's running on top of an existing kubernetes deployment), there seem to be GCP-specific components described in the README and circleci tasks.

A few questions:

Does anybody currently use this for an AWS Pangeo deployment?
Do we have an idea of what would need to change to support AWS instead of GCP?
How should we support other cloud providers for these deployment repos? (Different repos? Branches? Support both with a configuration switch?)

Particularly interested in @dsludwig, @jacobtomlinson, @yuvipanda thoughts

**Comment by jhamman** [comment]
The nasa deployment is up and running on aws eks. Closing...

**Comment by rsignell-usgs** [comment]
Are we ready to switch pangeo.esipfed.org over, or should we wait a while?

**Comment by jhamman** [comment]
@rsignell-usgs - I think we will be ready next week. Let's open a new issue to coordinate that.
