### ISSUE TITLE
Keras as part of the ocean.pangeo environment?

### ISSUE THREAD

**Issue by valentina-s** [pangeo-data/pangeo-cloud-federation#370]
@rabernat  I would like to inquire whether we can have the keras (deep learning) library pre-installed on the ocean.pangeo.io. I would need it for the Oceanhackweek Machine Learning Tutorial, but I guess it could be useful for other deep learning tutorials on the platform. Clearly, CPU jupyter hub might not be the best place for intense deep learning runs, but for introducing researchers to the basic functionality should be good enough. If I neeI to add it to some .yaml file, please, point me to it.

**Comment by rabernat** [comment]
Valentina, thanks for bring this up. Tensorflow, keras, and pytorch all used to be installed in our pangeo base-notebook environment (https://github.com/pangeo-data/pangeo-stacks/blob/master/pangeo-notebook/binder/environment.yml). Unfortunately, they were removed in https://github.com/pangeo-data/pangeo-stacks/pull/67 for reasons I don't yet understand. Hopefully @scottyhq will weigh in.

We definitely must get them back one way or another. I personally depend on these heavily.

**Comment by rabernat** [comment]
I'm not sure this can really be closed until we point ocean at the correct image and re-deploy.

I see three distinct options:
1. Add the ML libs back to the `pangeo-notebook` image, (this is what https://github.com/pangeo-data/pangeo-stacks/pull/69 did).
1. Create a new image (e.g. `pangeo-ml`) in pangeo stacks and base ocean.pangeo.io on top of that.
1. Add the ML libs directly in the ocean config in this repo.

I am no longer an expert on the best practices here. I would welcome the advice of @scottyhq, @tjcrone, and @jhamman and which of these options is best.

**Comment by tjcrone** [comment]
I guess the question we need to resolve is why they were removed in the first place. I do not know the answer do this. Does anyone here know? If these can simply be added back in to the conda env, this would seem like the best solution. Is there any reason why we cannot do this?

**Comment by jhamman** [comment]
I think this has been fixed upstream in pangeo stacks (https://github.com/pangeo-data/pangeo-stacks/pull/69). At this point, we just need to propagate the change through to these hubs.

**Comment by jhamman** [comment]
see #389
