### ISSUE TITLE
Server startup failure on staging.pangeo.io

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cloud-federation#4]
Spawn failed: HTTPSConnectionPool(host='10.4.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/staging/persistentvolumeclaims (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff25d601438>: Failed to establish a new connection: [Errno 111] Connection refused',))

![2018-10-24_16-03-51](https://user-images.githubusercontent.com/1872600/47458013-93433b80-d7a6-11e8-988e-052cfc287b38.png)

**Comment by dsludwig** [comment]
Interesting.. I was able to get a server started. The error you're seeing is the hub server failing to connect to the Kubernetes API server, which is surprising.

**Comment by rsignell-usgs** [comment]
@dsludwig, it's working for me this morning, so I guess it's an intermittent problem.   I'll close and we can reopen if it happens again.
