### ISSUE TITLE
Move to current master of hubploy

### ISSUE THREAD

**Issue by yuvipanda** [pangeo-data/pangeo-cloud-federation#40]
Currently, this is using hubploy from @dsludwig's fork. We've incorporated all the changes from the fork to hubploy master / repo2docker. We should try move this back to using hubploy master.

This should ideally happen at the same time as consolidating all hubs into one repo

**Comment by jhamman** [comment]
closed by https://github.com/pangeo-data/dev.pangeo.io-deploy/pull/49
