### ISSUE TITLE
Widget trouble on ocean.pangeo.io

### ISSUE THREAD

**Issue by naomi-henderson** [pangeo-data/pangeo-cloud-federation#407]
@rabernat and I are trying to implement a simple, but very useful Data Catalog for our
Pangeo CMIP6 collection in Google Cloud.  It works brilliantly on our local jupyterhub installations - here is a screenshot to give you an idea:

![screenshot](http://fletcher.ldeo.columbia.edu/catalogs/qgrid.png)

The [qgrid](https://github.com/quantopian/qgrid) package displays a pandas dataframe in a widget and efficiently allows the user to filter, search and sort the columns and/or select rows and then can easily save the chosen data in another dataframe.

The bad news is that `qgrid` hasn't been updated in awhile and recent versions of `ipywidgets` seem to break the widget which then just displays 'Loading widget...' - 
no dataframe view.  See [this `qgrid` issue](https://github.com/quantopian/qgrid/issues/259) and [this `plotly` issue](https://github.com/plotly/plotly.py/issues/1659).

And ... I cannot get it to work on ocean.pangeo.io which is really where we would really like to test it out.  As with all widgets, getting it to work involves installing components both in 
the webserver and the kernel. I have tried various versions of ` ipywidgets` and labextensions `qgrid` and `@jupyter-widgets/jupterlab-manager`, but am not getting anywhere - still just 'Loading  widget...'  

Suggestions anyone?

**Comment by charlesbluca** [comment]
This was able to get qgrid running on the latest version of JupyerLab (in a Binder) for me:

https://github.com/quantopian/qgrid/issues/271#issuecomment-530287585

It seems like the problem is more on the maintainers of the project to merge a pull request that fixes the issue, but it seems like the maintainers have largely been inactive over the past few months.

**Comment by charlesbluca** [comment]
Can confirm that running the following lines in Ocean terminal got the qgrid widget up and running for me:

```
pip install qgrid
git clone --depth=1 https://github.com/qzchenwl/qgrid qgrid.git
jupyter labextension install qgrid.git/js/
```

Obviously this is only a quick fix and it only works as long as the forked version is maintained, but perhaps if we get in contact with [Quantopian](https://www.quantopian.com) we can get someone to merge the PR which fixes this issue.

**Comment by naomi-henderson** [comment]
@charlesbluca , Fantastic! The 'qzchenwl' fix works on `ocean.pangeo.io` with your three line patch. Thank you very much.  Now I will try get the quantopia/qgrid follks to merge the PR.
