### ISSUE TITLE
Deployment failures following #415

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#418]
I just merged #415 and things did not go well. We're getting an upgrade failure coming from some recent changes in JupyterHub:

```
Fetching cluster endpoint and auth data.
kubeconfig entry generated for dev-pangeo-io-cluster.
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "pangeo-data" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading pangeo from repo https://pangeo-data.github.io/helm-chart/
Deleting outdated charts
UPGRADE FAILED
Error: Deployment.apps "proxy" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
Error: UPGRADE FAILED: Deployment.apps "proxy" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 65, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 128, in deploy
    version
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 58, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'dev-staging', 'dev-staging', 'pangeo-deploy', '-f', 'deployments/dev/config/common.yaml', '-f', 'deployments/dev/config/staging.yaml', '-f', 'deployments/dev/secrets/staging.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=bf2b025', '--set', 'pangeo.jupyterhub.singleuser.image.name=gcr.io/pangeo-181919/dev-pangeo-io-notebook']' returned non-zero exit status 1.
Exited with code 1
```

I'm pretty sure these are coming from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1401. If @consideRatio is around, maybe he can help point us in the right direction. If not, we need to dig into this a bit to see what this means. This error is described in the JupyterHub chart so presumably there is a simple fix: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/4300ff5bb82e56eb0304f11e96e0e7138a60c7d0/jupyterhub/values.yaml#L88-L113

**Comment by jhamman** [comment]
Explicitly setting `jupyter.proxy.rollingUpdate: ` to an empty value did not help. I haven't been able to reproduce this locally (outside of hubploy). @yuvipanda - have you deployed  jupyterhub/zero-to-jupyterhub-k8s#1401 to your data8 hubs yet?

**Comment by consideRatio** [comment]
@jhamman =/ sorry, yes I ran into that myself after https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1401 and thought it was fixed in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1404. And I tracked down that the pangeo chart version `19.09.26-dd6574b` use the z2jh helm chart `0.9-7738a96`, which should been fine I thought.

**Comment by consideRatio** [comment]
Did you get the same error after you changed the value? Hmmm...

**Comment by jhamman** [comment]
Yes, same error when setting the rollingUpdate to an empty string. https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/808

To be clear though, I didn't expect this to work since the value should be already set (we don't overwrite the proxy defaults in this section).

**Comment by consideRatio** [comment]
If you do `helm template ` to render the templates, is the proxy deplyment template containing an updateStrategy field that has a `rollingUpdate: null` entry? If you don't thats the crux.

```
# shell command i used to debug something ...
helm template jupyterhub --set proxy.secretToken=test templates/proxy/deployment.yaml | grep "Source: jupyterhub/templates/proxy/dep" -A 100
```

**Comment by consideRatio** [comment]
can you try run a template command on the pangeo chart to render the proxy deployment?

Also question: did you or did you not use `--force` during helm upgrade? I'm typically using `--force` as it is a very soft force that simply makes sure to recreate things that typically shouldnt be changed but sure can be, i think.

**Comment by consideRatio** [comment]
My debugging idea requires a lot of pangeo chart + cloud federation knowledge, I lack too much to quickly do it, so I'll describe it.

1. Whatever chart that is failing, instead of making a `helm upgrade` on that, make a `helm template` specifying exactly the same --values in the same order as you did for the helm upgrade.

I suspect that the proxy deployment is receiving values that does not contain `rollingUpdate: null` as it should to avoid this error.

**Comment by jhamman** [comment]
Thanks @consideRatio - I'll give that a go now. Will report back asap.

**Comment by consideRatio** [comment]
It could be that a sequence of value file merges passed to `helm` leads to this field is removed from the final values passed to the chart rendering =/

Then, the solution for the short term is to do a final `--set` of the value for example.

**Comment by jhamman** [comment]
```bash
helm template  pangeo-deploy -f ./deployments/dev/config/common.yaml -f deployments/dev/config/staging.yaml -f deployments/dev/secrets/staging.yaml --set pangeo.jupyterhub.singleuser.image.tag=bf2b025 --set pangeo.jupyterhub.singleuser.image.name=gcr.io/pangeo-181919/dev-pangeo-io-notebook
```
[dump.txt](https://github.com/pangeo-data/pangeo-cloud-federation/files/3663912/dump.txt)

I don't see `rollingUpdate` anywhere in the proxy sections.

**Comment by consideRatio** [comment]
For this template rendering, was the requirements.yaml set to depend on a recent z2jh, post #1401 and #1404?

Had `helm dep up` been run to update the dependency stuff? Dont remember if that is required or if it would complain or not...

**Comment by jhamman** [comment]
Yes, I ran helm dependency update before. 

Looks like we have this hierarchy: 
- `pangeo-deploy (local chart, current staging branch)`
  - `pangeo-19.09.26-dd6574b`
    - `jupyterhub-0.9-445a953`

btw, if I do `helm upgrade ... --dry-run --debug`, I also don't see a proxy section or a rollingUpdate key.

**Comment by consideRatio** [comment]
Hmmmm, but then you have not reached z2jh#1401 yet I think.

**Comment by jhamman** [comment]
I'm pretty sure `4300ff5` is equivalent to JupyterHub master right now: 

- https://jupyterhub.github.io/helm-chart/#development-releases-jupyterhub
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/4300ff5bb82e56eb0304f11e96e0e7138a60c7d0

is z2jh#1401 not in master yet? I thought it landed on Sep 10, 2019 (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/9c15a42b1227f3b54826f273f1689e4dc8c8e12e).


Edit: wait, things don't seem to match as expected. Looking into this more.

**Comment by consideRatio** [comment]
Everything you see is in master, but you wrote:

pangeo-deploy (local chart, current staging branch)
pangeo-19.09.26-dd6574b
jupyterhub-0.9-445a953

And I tracked 445a953 to be from 18th of June which is a lot earlier than #1401. Hmmmm.

**Comment by consideRatio** [comment]
It would be nice to have automated mapping :p

From pangeo chart to z2jh chart and to JupyterHub

**Comment by jhamman** [comment]
Yeah, you're right. I'm not trying to figure out why we're picking up jupyterhub-0.9-445a953. This is not what is listed in the pangeo chart: `version: "0.9-7738a96"`.

https://github.com/pangeo-data/helm-chart/blob/29589be538ae64fd27d3c0ae6396d4fefbe8fdbd/pangeo/requirements.yaml#L4

**Comment by jhamman** [comment]
Okay, my working theory is this:

`pangeo-19.09.26-dd6574b` is broken. It appears it picked up a pretty old version of the z2jh chart. 

I updated the pangeo chart (now at `19.09.27-86dd66c` which is also jhub master). Things are working locally so I'll see if they deploy for all the hubs.

**Comment by consideRatio** [comment]
The helm chart dependency chain from pangeo-cloud-federation's current master leads to a very recent z2jh release.
- (STAGING BRANCH) https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/pangeo-deploy/requirements.yaml#L3
  - https://github.com/pangeo-data/helm-chart/blob/dd6574b/pangeo/requirements.yaml#L4
    - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commits/7738a96

- (PROD BRANCH) https://github.com/pangeo-data/pangeo-cloud-federation/blob/prod/pangeo-deploy/requirements.yaml#L3
  - https://github.com/pangeo-data/helm-chart/blob/37d387f/pangeo/requirements.yaml#L4
    - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commits/445a953

**Comment by consideRatio** [comment]
When you say the "pangeo chart" do you mean the pangeo-data/helm-chart ? I'm not sure how pangeo-cloud-federation relate.

**Comment by jhamman** [comment]
Yes, the pangeo-cloud-federation repo uses the pangeo-data/helm-chart which obviously uses the z2jh chart. So that's the hierarchy.

I just redeployed all the hubs. The one I'd been working with deployed successfully (https://staging.hub.pangeo.io). The others failed with the same error but I may just need to roll them back before redeploying.

**Comment by jhamman** [comment]
I think we're good now! For whatever reasons, I think `helm upgrade` needed the `--force` to get things going but we're mostly working again. @scottyhq and @rsignell-usgs, you'll need to follow these steps on the aws hubs:

```bash
Basically I did this
helm list  # pick a revision for staging deployments before today
helm rollback $deployment $revision
helm upgrade --wait --install --namespace $deployment-staging $deployment-staging pangeo-deploy -f ./deployments/$deployment/config/common.yaml -f deployments/$deployment/config/staging.yaml -f deployments/$deployment/secrets/staging.yaml --force
```

**Comment by jhamman** [comment]
@consideRatio - thank you very much for your help here. I'm still a bit befuddled by the old version of z2jh in the pangeo chart but that seems to be behind us.

**Comment by jhamman** [comment]
I'm still not 100% sure what went wrong here but it seems we needed `--force` to upgrade to the new z2jh chart. Running

```
helm upgrade --wait --install --namespace $deployment-$branch $deployment-$branch pangeo-deploy -f ./deployments/$deployment/config/common.yaml -f deployments/$deployment/config/$branch.yaml -f deployments/$deployment/secrets/$branch.yaml --force
```

did the trick but required manual intervention for all GCP hubs. The AWS hubs will need to be redeployed following a similar procedure. 

I recorded the helm state before deploying in case we need to roll back manually:

```
NAME         	REVISION	UPDATED                 	STATUS  	CHART              	APP VERSION	NAMESPACE
dev-prod     	41      	Sun Sep  8 17:21:13 2019	DEPLOYED	pangeo-deploy-0.1.0	1.0        	dev-prod
hydro-prod   	41      	Sun Sep  8 17:21:38 2019	DEPLOYED	pangeo-deploy-0.1.0	1.0        	hydro-prod
ocean-prod   	43      	Sun Sep  8 17:21:25 2019	DEPLOYED	pangeo-deploy-0.1.0	1.0        	ocean-prod
```

#424 was my last merge. Again, all the GCP hubs passed and the AWS hubs did not. For whatever reason, the Azure hubs never ran into this problem.

**Comment by consideRatio** [comment]
@jhamman thanks for documenting this experience! I'm still learning on how helm and kubernetes interact and what can happen. From my experience, it is very clear in my mind, that when using a Z2JH helm chart at least, the use of `--force` is a very good practice to avoid issues.

I hope we can better catch these issues by making some install->upgrade CI tests in Z2JH. After https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1422 that comes next.

**Comment by scottyhq** [comment]
finally had a bit of time to diagnose the remaining upgrade failures on the AWS hubs. The following recipe works for a manual upgrade:

```
cd pangeo-cloud-federation 
deployment=nasa 
branch=staging
git pull upstream $branch
helm history $deployment-$branch --max=10 --col-width=0 #pick latest "deployed status" (212)
helm rollback $deployment-$branch 212 
cd pangeo-deploy ; helm dependency update ; cd ../
helm upgrade --wait --install --namespace $deployment-$branch $deployment-$branch pangeo-deploy -f ./deployments/$deployment/config/common.yaml -f deployments/$deployment/config/$branch.yaml -f deployments/$deployment/secrets/$branch.yaml --force
```

The key to the issue (I think) is that our upgrades on circleci are not running `helm dependency update` and therefore not getting the new jupyterhub config.

Running the above code locally, we see:
```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "pangeo" chart repository
...Successfully got an update from the "binderhub" chart repository
...Successfully got an update from the "jupyterhub" chart repository
...Successfully got an update from the "stable" chart repository
```

But on circleci the jupyterhub updates aren't showing:
https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/806
```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "pangeo-data" chart repository
...Successfully got an update from the "stable" chart repository
```


@jhamman and @yuvipanda - this seems to be the relevent code in hubploy
https://github.com/yuvipanda/hubploy/blob/f5a1d2f9aaa98d1929570458a92e02b9eba41b1b/hubploy/helm.py#L36

**Comment by scottyhq** [comment]
fixed by adding the following line
https://github.com/pangeo-data/pangeo-cloud-federation/blob/8893e4c7a7db7c2d06bb21badc3979d21d307776/.circleci/config.yml#L227

Still had to run locally `helm rollback` to the most recent 'Deployed' state and then `helm upgrade` with the `--force` flag in order for subsequent circleci builds to work.

**Comment by jhamman** [comment]
Thanks @scottyhq - this was quite odd but seems to have done the trick. You're a wizard!
