### ISSUE TITLE
Add support for nbdime on ocean.pangeo.io 

### ISSUE THREAD

**Issue by brian-rose** [pangeo-data/pangeo-cloud-federation#456]
[nbdime](https://nbdime.readthedocs.io/en/latest/) is a great tool for rich visual diffs of Jupyter notebooks. It would be great to have access to this from the ocean.pangeo.io Jupyterhub / jupyterlab.

I'm preparing some tutorials on this for the CMIP6 Hackathon over here:
https://github.com/brian-rose/notebook_diff_tutorial

**Comment by rabernat** [comment]
Please go ahead and make a PR to add it to the environment here: https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments/ocean/image/binder

You can just edit the environment.yml file in github.
