### ISSUE TITLE
OOI deploy failing

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#460]
@tjcrone, can you take a look at the OOI cluster? The helm deploy step has started failing. We've had to merge PRs regardless to keep the CMIP6 hack going but it would be great to fix things up when you get a chance.

**Comment by tjcrone** [comment]
@jhamman thanks for letting me know. This should be fixed now. Would be cool if we could set up the CircleCI configuration to send a notification to a particular user when a particular step fails. I looked briefly but didn't find a way to do this on a step-by-step basis.

**Comment by tjcrone** [comment]
The best way to do this might be to test the return value of the hubploy command inside the command list, and send an email using [SendGrid](https://sendgrid.com/) or [Mailgun](https://www.mailgun.com/email-api) as suggested [here](https://support.circleci.com/hc/en-us/articles/360007444314-Sending-email-from-a-container) if hubploy returns non-zero. I might have time to try this out later today. Any thoughts?
