### ISSUE TITLE
Staging build failed

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#510]
https://app.circleci.com/jobs/github/pangeo-data/pangeo-cloud-federation/1026

```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Too long with no output (exceeded 10m0s): context deadline exceeded
```

Easy solution is to bump the timeout in the circleci config and trigger a rebuild.

**Comment by TomAugspurger** [comment]
This problem has been fixed, but another has arisen so I'll reuse this issue :)

https://app.circleci.com/jobs/github/pangeo-data/pangeo-cloud-federation/1034

```
Deleting outdated charts
2020/01/26 01:09:42 Warning: Merging destination map for chart 'dask-gateway'. Cannot overwrite table item 'extraConfig', with non table value: map[]
2020/01/26 01:09:42 Warning: Merging destination map for chart 'dask-gateway'. Cannot overwrite table item 'extraConfig', with non table value: map[]
2020/01/26 01:09:42 Warning: Merging destination map for chart 'pangeo'. Cannot overwrite table item 'extraConfig', with non table value: map[]
2020/01/26 01:09:42 Warning: Merging destination map for chart 'dask-gateway'. Cannot overwrite table item 'extraConfig', with non table value: map[]
2020/01/26 01:09:42 Warning: Merging destination map for chart 'pangeo'. Cannot overwrite table item 'extraConfig', with non table value: map[]
2020/01/26 01:09:42 Warning: Merging destination map for chart 'dask-gateway'. Cannot overwrite table item 'extraConfig', with non table value: map[]
UPGRADE FAILED
Error: timed out waiting for the condition
Error: UPGRADE FAILED: timed out waiting for the condition
Traceback (most recent call last):
```

A bit of googling suggested this error came up when YAML files mixed up a `{}` and `[]`.

**Comment by tjcrone** [comment]
Yeah I have seen this a few times for other charts. Sometimes the spec changes from a list to a dict, or vice versa, and the chart breaks. Pretty easy to recover from but annoying. Here we are at the bleeding edge.

**Comment by TomAugspurger** [comment]
Yep. #515 fixed this. I needed to manually delete the gateway pods before the deployment would succeed: https://app.circleci.com/jobs/github/pangeo-data/pangeo-cloud-federation/1039
