### ISSUE TITLE
Monthly Pangeo Cloud Ops Telecon

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#526]
We will have our regularly scheduled Cloud Ops telecon on Monday, Feb. 10, at 8:30am PST. More details here: https://pangeo.io/meeting-notes.html. Please feel free to add agenda items ahead of time.

Cross posting from https://discourse.pangeo.io/t/cloud-deployments-working-group/342/13

cc @scottyhq @rabernat @guillaumeeb  @kaedonkers @yuvipanda @consideRatio @amanda-tan @salvis2 @tjcrone @TomAugspurger @mrocklin

**Comment by consideRatio** [comment]
Ive marked it my calendar! Looking forward to it!

**Comment by jhamman** [comment]
Reminder, out next meeting is tomorrow (Monday) at 9:30 PDT. Details in the discourse post above.

**Comment by yuvipanda** [comment]
I'll unfortunately miss this one due to Timezone shenanigans. See you at the next one!
