### ISSUE TITLE
I/O error when saving notebooks on ocean.pangeo

### ISSUE THREAD

**Issue by AndrewILWilliams** [pangeo-data/pangeo-cloud-federation#553]
I'm currently using the ocean.pangeo.io server to run some analysis on the cesm large ensemble data stored on AWS (https://medium.com/pangeo/cesm-lens-on-aws-4e2a996397a1). It's been working fine for the past month or two, however since yesterday I keep getting lots of file save errors on my notebooks:

```
File Save Error for djf_sens_hist.ipynb
Unexpected error while saving file: .../djf_sens_hist.ipynb disk I/O error
```

However then my only choice is to close without saving, which can cause even more bugs with the notebooks in future in my experience.

Similarly, if I try to duplicate a notebook I get an error:

```
Duplicate file
Invalid response: 500
```

Then sometimes it will still duplicate the notebook, and other times it won't.

Some of these errors seem to memory-related, but I don't know how I'd identify the source of them or how to fix it, any help appreciated! 

Also, fyi, I am not storing any files on my workspace except for one LANDFRAC file of ~200Mb, so I doubt this is causing any memory errors.

First issue for me so let me know if this is being submitted correctly! Thanks again.

**Comment by AndrewILWilliams** [comment]
Ok now when I try to go on the server I get:

```
503 : Service Unavailable
Your server appears to be down. Try restarting it from the hub
```

I've tried stopping my server from the hub and restarting it but no joy.

**Comment by blwhite-climML** [comment]
I also received a 503 error. I logged out and restarted ok but now unable to open NBs. It seems that the file system is showing as being full on /home/jovyan.

Not sure what is taking up the space (my individual directory is only 5G). 

Is this possibly due to the ocean.pangeo fs being maxed out?

**Comment by AndrewILWilliams** [comment]
@bwhite-unc seems like we've got the same issue, hopefully it's only temporary.

**Comment by AndrewILWilliams** [comment]
@bwhite-unc my notebooks are working now, is this the same with you ?

**Comment by jhamman** [comment]
I'm fairly sure you were both running into an issue with the filesystem being full. We're discussing long term fixes here: https://discourse.pangeo.io/t/i-o-errors-out-of-disk-space/428/6

In the meantime, I've increased the size of our NFS server and things should be working again.
