### ISSUE TITLE
Closing / shutting down dask-gateway clusters

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#583]
Currently, in a jupyterlab session`Kernel-->restart` kernel also closes a users active dask-gateway scheduler and workers. I noticed that if a user runs `cluster.close()` or `cluster.shutdown` before running `client.close()`. the command returns immediately and is successful, but after a few seconds displays the following warning/error:

```
distributed.client - ERROR - Failed to reconnect to scheduler after 10.00 seconds, closing client
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
concurrent.futures._base.CancelledError
```

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
It looks like GatewayCluster handles this for for clients it creates with `get_client()` at https://github.com/dask/dask-gateway/blob/b4c3d1899283e1bbc23e4a28f585a9439c69a188/dask-gateway/dask_gateway/client.py#L939-L941, but this doesn't handle Clients created elsewhere and attached to the GatewayCluster.

@jcrist do you have a prior on how to handle this? My guess is that GatewayCluster shouldn't have to have any code for informing clients that they should close. That should be handled in `Scheduler.close`. Does that sound right?

**Comment by jcrist** [comment]
Yeah, one of the reasons `get_client()` was added is that distributed's clients aren't always the best about cleaning themselves up. This should be fixable in distributed, but currently you're likely to see these warnings.

**Comment by jcrist** [comment]
To be clear, I think the fix should be made upstream to distributed, `get_client` is likely to be deprecated once distributed is more robust about handling this.

**Comment by TomAugspurger** [comment]
OK. I'll open an issue in distributed.

**Comment by TomAugspurger** [comment]
Actually, https://github.com/dask/distributed/pull/3239 seems to be what we would want.

**Comment by TomAugspurger** [comment]
Closing this since it should be handled upstream.
