### ISSUE TITLE
Moving to a single gcp-us-central2 hub 

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#599]
This repo currently has three JupyterHub deployments in GCP us-central2:

- ocean.pangeo.io
- hydro.pangeo.io
- hub.pangeo.io

I'd like to propose we tear down the hydro and hub deployments and rename ocean.pangeo.io to `gcp-uscentral2.pangeo.io`. We can setup redirects for all three hubs to this new url.

Advantages:
- cheaper
- less maintenance overhead
- advances in environment specification tools have made it much easier to provide multiple profiles on the same deployment.

Disadvantages:
- takes some time now
- will require some re-education / communication.

cc @rabernat, @bartnijssen, @scottyhq, @TomAugspurger

**Comment by scottyhq** [comment]
I like this idea. Who is currently using hub.pangeo.io and hydro.pangeo.io? See https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/icesat2/config/common.yaml#L88 if you want to go the route of adding various images to gcp-uscentral2.pangeo.io

**Comment by rabernat** [comment]
I favor this. I'd also like to combine it with a unified approach to auth and home directories.

**Comment by jhamman** [comment]
closed by #625
