### ISSUE TITLE
Suppress distributed warnings

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo-cloud-federation#600]
Is there a way to suppress the warnings that are generated by the distributed system?

Stuff like:

```
distributed.scheduler - INFO - Remove worker tcp://10.32.19.7:40273
distributed.core - INFO - Removing comms to tcp://10.32.19.7:40273
distributed.core - INFO - Event loop was unresponsive in Scheduler for 5.62s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.scheduler - INFO - Remove worker tcp://10.32.20.13:37963
distributed.core - INFO - Removing comms to tcp://10.32.20.13:37963
distributed.core - INFO - Event loop was unresponsive in Scheduler for 7.85s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.scheduler - INFO - Register tcp://10.32.8.8:44753
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.8.8:44753
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://10.32.43.21:40937
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.43.21:40937
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://10.32.11.7:43025
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.11.7:43025
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://10.32.54.7:32847
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.54.7:32847
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://10.32.7.8:35239
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.7.8:35239
distributed.core - INFO - Starting established connection
```

Using the following does not work.
``` 
import warnings
warnings.filterwarnings('ignore')
```

**Comment by TomAugspurger** [comment]
Those aren’t warning, those are log messages. You can configure logging in your dask config: https://docs.dask.org/en/latest/debugging.html#logs

**Comment by dhruvbalwada** [comment]
Thanks Tom. I think I understand the theory of what is going on now, but have been having trouble to practically get the logging messages to stop showing up. 

I tried to set the logging to `error`, by running : `dask.config.set({'distributed.scheduler.logging': "error"})` , but I still keep getting the messages that seem like `info` level messages. 

Can someone please post some code on how to get the logging messages to stop? or config yaml file that they use?

**Comment by TomAugspurger** [comment]
You might need to import dask and do the `dask.config.set` prior to
importing distributed. Some of those values may be read at import time.

I'm also not sure if setting `distributed.scheduler.logging: "error"` will
work. Try

```python
dask.config.set({"logging.distributed": "warning"})
```

Setting things on a per-module basis like `distributed.scheduler` I think
requires additional work, but hopefully isn't needed here.

**Comment by scottyhq** [comment]
@dhruvbalwada - where are you running your code / what image are you using? For pangeo docker images we set the logging in this file https://github.com/pangeo-data/pangeo-docker-images/blob/master/base-image/dask_config.yml#L21

**Comment by dhruvbalwada** [comment]
@TomAugspurger - Thanks again. Setting the config prior to importing dask distributed worked.

@scottyhq  - I am using ocean.pangeo.io
