### ISSUE TITLE
Permissions issue with Google Cloud Storage

### ISSUE THREAD

**Issue by chiaral** [pangeo-data/pangeo-cloud-federation#615]
Between today and a month ago, I noticed a change in permissions for google cloud storage. I have a bucket, `pangeo-cmip6-cape`, for which I have a service account access token to write. Before, from ocean.pangeo.io, I could **read** this bucket with the default credentials (no service account). However, now I am getting an error

```python
fs = gcsfs.GCSFileSystem(project='pangeo-181919')
file_list = fs.ls('pangeo-cmip6-cape/')
```

I get
```
OSError: Forbidden: https://www.googleapis.com/storage/v1/b/pangeo-cmip6-cape/o/
Primary: /namespaces/pangeo-181919.svc.id.goog with additional claims does not have storage.objects.list access to the Google Cloud Storage bucket.
```

If I replace `fs` with a `GCSFileSystem` associated with my service account token, it works. This is fine,  but I thought I would report this change in behavior.

**Comment by TomAugspurger** [comment]
Hmmm, I wonder if that's my fault from https://github.com/pangeo-data/pangeo-cloud-federation/issues/610#issuecomment-636874215. I'm not entirely sure though.

I'll poke around with the permissions a bit.

**Comment by TomAugspurger** [comment]
OK, it was probably my fault, sorry! :)

I fixed on ocean-staging by granting the `pangeo` Google service account the `storage.ObjectViewer` role and then linking the KSA & GSA:

```
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:pangeo-181919.svc.id.goog[ocean-staging/pangeo]" \
  pangeo@pangeo-181919.iam.gserviceaccount.com

kubectl annotate serviceaccount \
  --namespace ocean-staging \
   pangeo \
   iam.gke.io/gcp-service-account=pangeo@pangeo-181919.iam.gserviceaccount.com
```

I'm thinking about how to fix this for ocean.pangeo.io. Will report back in a bit.

**Comment by chiaral** [comment]
I actually don't mind as it is right now, my bucket requires the token to be accessed so it makes sense to have the same behaviour to read the files, I suppose, I just noticed the change and wanted to report it in case anyone got stuck on it.

As far as I am concerned, nothing needs to be reverted to the old set up. But whatever is the correct/expected behaviour sounds good to me!

**Comment by rabernat** [comment]
We just hit a similar issue:

```python
from intake import open_catalog

cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/altimetry.yaml")
ds = cat['j3'].to_dask()
```

```
Error: Forbidden: https://www.googleapis.com/download/storage/v1/b/pangeo-cnes/o/alti%2Fj3%2F.zmetadata?alt=media
b'pangeo@pangeo-181919.iam.gserviceaccount.com does not have serviceusage.services.use access to the Google Cloud project.'
```

So it looks like requester pays data doesm't work. This is pretty serious, as it impacts the production hub.

**Comment by TomAugspurger** [comment]
Hmm sorry about that. Can you try again? Just ran

```
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:pangeo-181919.svc.id.goog[ocean-prod/pangeo]" \
  pangeo@pangeo-181919.iam.gserviceaccount.com

kubectl annotate serviceaccount \
  --namespace ocean-prod \
   pangeo \
   iam.gke.io/gcp-service-account=pangeo@pangeo-181919.iam.gserviceaccount.com
```

**Comment by TomAugspurger** [comment]
I guess the error is a bit different. `serviceusage.services.use` rather than `storage.objects.list`. I'll need to think about this a bit, since we don't want requests done by these workers to be billed back to us? At least not for arbitrary buckets?

**Comment by TomAugspurger** [comment]
One thing I'm not sure about: what project was being used in the old setup? Was it `pangeo-181919`? If so, then we won't be any worse off allowing our jupyterhub pods make requester pays requests from our account.

@rabernat here's the command to run if you're comfortable with that.

```
gcloud projects add-iam-policy-binding pangeo-181919 \
  --member serviceAccount:pangeo@pangeo-181919.iam.gserviceaccount.com \
  --role roles/serviceusage.serviceUsageConsumer
```

**Comment by rabernat** [comment]
> One thing I'm not sure about: what project was being used in the old setup? Was it `pangeo-181919`?

Yes

I'm thinking through the implications here. Requester pays is annoying. I really want to allow `serviceusage.serviceUsageConsumer` only when it doesn't actually cost money!

I'm going to enable it for now.

**Comment by rabernat** [comment]
Yes, that fixed it! Thanks a million Tom!

**Comment by TomAugspurger** [comment]
I think this is fixed now.
