### ISSUE TITLE
Decomissioning hydro.pangeo.io and hub.pangeo.io

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#616]
hydro.pangeo.io and hub.pangeo.io are being decommissioned on Monday, June 22, 2020.  

More details here: https://discourse.pangeo.io/t/migration-of-ocean-pangeo-io-user-accounts/644

I am using this issue to ping users of these hubs via their github handle. 

### Getting your data/notebooks off pangeo.pydata.org
If you have data/notebooks on this JupyterHub that you may want to keep, the following snippet may be of use to download your current home directory.

```bash
find . -type f -name '*.ipynb' -print | grep -v '.ipynb_check' > list_of_notebooks
tar -cvf backup.tar -T list_of_notebooks
gzip backup.tar
# download the backup.tar using jupyterlab interface
```

### hydro.pangeo.io users
@jhamman @arbennett @bartnijssen @chrimerss @naddor @kratzert @shahryaramd @anniezac @spestana @cassielumbrazo @medercc @d-reynolds @hishameldardiry @harrellj @victorialy @greynearing @azartakeshi @scottyhq @guyshalev @shmathi @shelbahr @auraoupa @andywood @darothen @koryswabb @lesteve @martynpclark @virdi @emadhabib2018 @jennybyrd @pjbutcher @jessicalundquist @conor-tyson @catherine-m-breen @rsignell-usgs @meganmason @maggik @camilaabe @youngblood575 @joshuamorell208 @yesicaleo @4everdrew @sgoeking @krabeler @collinjroland @edugonzalu @allisonvincent @lrvprasad @bwilder95 @davidchoi76 @djgagne @jsosa @mg1989 @christinab @zhiyuli @bwhite-unc @nilocj @danhirst98 @akan72 @ruiwu08 @mkasari @praful126 @driftclouds @hayleegaddy @aegustaf @izzihinks @sam1230 @silianbraille @nikhil-vytla @chonnyrama @cxd00 @laurenhayh2o @sydneyaddison @jbusecke @castronova @ashleymedin @emiliom @renjianning @jhkennedy @aaraney @bwhite-envfluids @kmpaul @fperez @lheagy @laureloak @emscience @alicecima @facusapienza21 @jonathan-taylor @apage43 @abat16

### Hub.pangeo.io users
@rsignell-usgs @dsludwig @rabernat @choldgraf @yuvipanda @jhamman @mrocklin @jacobtomlinson @adityarn @fmaussion @darothen @jmunroe @alexhilson @consideratio @nbren12 @jorisvandenbossche @tam203 @willirath @apawloski @abarciauskas-bgse @tomaugspurger @mariusvniekerk @tjcrone @guillaumeeb @raspstephan @quasiben @scottyhq @poplarshift @dhruvbalwada @aimeeb @jsadler2 @spencerahill @carreau @martindurant @lheagy @dpeterk @salvis2 @wtbarnes @guidov @cgentemann @niallrobinson @ogrisel @raybellwaves @observingclouds @kmpaul @sebastienlanglois @acannistra @nicwayand @marisolgr @gmaze @duncanwp @dshean @fperez @adeajayi-kunle

**Comment by jhamman** [comment]
@djgagne @jsosa @mg1989 @christinab @zhiyuli @bwhite-unc @nilocj @danhirst98 @akan72 @ruiwu08 @mkasari @praful126 @driftclouds @hayleegaddy @aegustaf @izzihinks @sam1230 @silianbraille @nikhil-vytla @chonnyrama @cxd00 @laurenhayh2o @sydneyaddison @jbusecke @castronova @ashleymedin @emiliom @renjianning @jhkennedy @aaraney @bwhite-envfluids @kmpaul @fperez @lheagy @laureloak @emscience @alicecima @facusapienza21 @jonathan-taylor @apage43 @abat16

**Comment by jhamman** [comment]
@dsludwig @rabernat @choldgraf @yuvipanda @jhamman @mrocklin @jacobtomlinson @adityarn @fmaussion @darothen @jmunroe @alexhilson @consideratio @nbren12 @jorisvandenbossche @tam203 @willirath @apawloski @abarciauskas-bgse @tomaugspurger @mariusvniekerk @tjcrone @guillaumeeb @raspstephan @quasiben @scottyhq @poplarshift @dhruvbalwada @aimeeb @jsadler2 @spencerahill @carreau @martindurant @lheagy @dpeterk @salvis2 @wtbarnes @guidov @cgentemann @niallrobinson @ogrisel @raybellwaves @observingclouds @kmpaul @sebastienlanglois @acannistra @nicwayand @marisolgr @gmaze @duncanwp @dshean @fperez @adeajayi-kunle

**Comment by Carreau** [comment]
Does deleting our data early helps ?
Thanks again for maintaining this all that time ! Amazing how far pangeo got !

**Comment by jhamman** [comment]
@Carreau - not particularly. If you don't care about your data, just leave it and we'll delete it when we take the hubs down.

**Comment by acannistra** [comment]
All good here, thanks for the public service!

**Comment by jhamman** [comment]
Reminder all. This is happening later today.

**Comment by choldgraf** [comment]
![](https://media1.giphy.com/media/rHR8qP1mC5V3G/giphy.gif?cid=ecf05e479cc031aa487055c5b958e236b3ec585c89e24590&rid=giphy.gif)

**Comment by lheagy** [comment]
👋 All good on my end. Thanks so much!!
