### ISSUE TITLE
Logging in to https://us-central1-b.gcp.pangeo.io/

### ISSUE THREAD

**Issue by cspencerjones** [pangeo-data/pangeo-cloud-federation#650]
I tried logging in using github (I used to use globus for ocean.pangeo.io). But now I just get `OAuth error: Access denied.` Am I doing something wrong? How can I troupbleshoot? Thanks for all your work on this!

**Comment by rabernat** [comment]
It looks like you have still not accepted your invitation to join the `us-central1-b-gcp` team: https://github.com/orgs/pangeo-data/teams/us-central1-b-gcp

As soon as you join it, your login will work.

**Comment by cspencerjones** [comment]
Ahh ok thanks! I missed the invite.
