### ISSUE TITLE
Dask gateway clusters freezing

### ISSUE THREAD

**Issue by chiaral** [pangeo-data/pangeo-cloud-federation#657]
It's hard to provide a reproducible example of this, but I have experienced it consistently since the change in cluster set up (since essentially I started posting all the issues!) 

I have a package I am running on cmip6 data that is rather intensive.
Before the switch from dask kubernetis to dask gateway I never had these problems. My set up work flawlessly with a certain # of workers and memory. Let's say that it took about 500 seconds for each year of analysis (I apply my calculation to one year at the time, in a loop).

Now when I run the same exact set of routines and packages, using the same set up of memory and workers, after a few years of correct behavior (which for me refers to a dashboard that looks to move smoothly through the tasks, and it looks like the dashboard I used to get using the dask kubernetis), I end up with this:

<img width="1440" alt="Screen Shot 2020-07-13 at 10 50 41 PM" src="https://user-images.githubusercontent.com/8453445/87378206-519a8b80-c55b-11ea-8b3a-c75ee0f0875e.png">

All tasks are concentrated in one worker. It's been stuck there for solid 10 min, it's not going to resolve this issue on its own, I usually have to stop everything, close the cluster and start a new one. (NOTE: I have a ```client.restart()``` in my loop, so I restart it every time I start a new year of calculations, but it doesn't seem to help). I also noticed that the scheduler CPU usage is at 100% during this time.

<img width="1440" alt="Screen Shot 2020-07-13 at 10 55 56 PM" src="https://user-images.githubusercontent.com/8453445/87378549-0765da00-c55c-11ea-8445-0374b67cf9b7.png">

One hunch I have is that it gets stuck when it has to start the `store` task (as you can see it didn't store anything yet), becuase based on my memory it usually start storing at that point (when it is about at that number of calc_cape_numpy tasks)

I welcome any input on how to try to figure out what is wrong with my set up and the new dask gateway set up.
Thanks!

**Comment by chiaral** [comment]
An update to this - 
After trying various configurations, the issue seems to resolve when I increase the worker's memory to 16GB (so more than the set up in Kubernetes where I was using the default value of 12GB). It has been working perfectly so far. So I will close the issue.

**Comment by rabernat** [comment]
Chiara thanks for sharing this issue. Although you resolved it by adding more memory, I think it still highlights the problem that, when dask_gateway fails, it doesn't fail very cleanly. In this case, your cluster got stuck in a broken state for a long time, rather than just crashing / shutting down cleanly. It would be nice to improve the user experience here.

**Comment by chiaral** [comment]
I agree. It also seems to "like more" if workers have more memory but less # of workers are fine. 

Before starting a few months ago, I tried a lot of # of workers combination with Kubernetes, and the 30 workers set up worked perfectly (maybe I could use 29 but let's say 30). I tried to use the same exact set up with Gateway (setting the memory of the worker to 12Gb first and 14Gb then) with 30 workers and, as I said, it would work for a bit, but then it would get stuck in that configuration and just hang there forever (it happened to hang for hours once). 
Now I am running 16Gb/23 workers, so the total memory is ~370Gb (not far from the Kubernetes configuration of 12Gbx30 workers) just spread out in a different way, and it works perfectly!

**Comment by chiaral** [comment]
Hello - this is just a quick update to this issue. 
Since last time I was working on pangeo - about a month ago - things are working much better. I am currently running on staging, but I can really see a difference in the dashboard. Tasks move more smoothly. The 'store' tasks in the image attached to the first part of this issue, that didn't kick in until towards the end back then, now it starts much earlier in the graph - as it should - so it releases memory and room for other taks. so dask gateway now seems to be much better than it used to be and things are running - at least for me - much smoother. so thanks SO much!
