### ISSUE TITLE
Auth0 fails for users with more than 30 github teams

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#683]
The GitHub API returns paginated responses with 30 results by default. So the rule that we depend on to add all of a user's github teams can fail to capture `pangeo-data/us-west2` or `pangeo-data/us-central1-b-gcp`:
https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/auth0/2-add-github-teams.js 

An example for iterating over response pages in Python is here:
https://github.com/pangeo-data/pangeo-cloud-federation/blob/d0fc5e00ba455e27c411646e88a0429890b1097d/.github/scripts/update_membership.py#L46-L58 

I think the solution we should adopt those is to only record `pangeo-data` organization teams. Sound good @rabernat @TomAugspurger ?

cc @rsignell-usgs who belongs to an astounding number of github teams ;)

**Comment by rabernat** [comment]
> I think the solution we should adopt those is to only record `pangeo-data` organization teams.

👍  Good call Scott! 

FWIW, we could also implement pagination in the rule itself, if we were better at javascript 😆 .

**Comment by TomAugspurger** [comment]
I'll take a look at this quick (since I need to use the aws hub and I'm locked out 😄)

**Comment by scottyhq** [comment]
> I'll take a look at this quick (since I need to use the aws hub and I'm locked out 😄) 

@TomAugspurger it's because you haven't signed up for Pangeo Cloud! :) https://pangeo.io/cloud.html#sign-up

**Comment by TomAugspurger** [comment]
I thought I was grandfathered in :) Hopefully I get accepted 🤞

**Comment by scottyhq** [comment]
Yeah last week we tied the aws-uswest2 hub access to the google sheet. Now that you're on it you should be good to log in!
