### ISSUE TITLE
Bring ML image to gcp cluster?

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#700]
The AWS cluster has a "ML Notebook" image, which points to https://github.com/pangeo-data/pangeo-docker-images/tree/master/ml-notebook. The GCP cluster does not. But many GCP users (e.g. @anirban89) want to do ML from GCP.

Is it as simple as adding this image to the profile list?

**Comment by TomAugspurger** [comment]
I think that + the things like `extra_resource_limits` at https://github.com/pangeo-data/pangeo-cloud-federation/blob/6df072a73577f7b1f1820e5e1cc25b0af1abae69/deployments/icesat2/config/staging.yaml#L33-L41.

It looks like we're set up to autoprovision node pools with k80s and v100s at https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/gcp-uscentral1b/autoprovisioning.json#L5-L6. I'm not sure how those are prioritized, but IIRC you can add additional attributes to the kubernetes pod to customize the scheduling.

**Comment by rabernat** [comment]
Believe it or not, some users may want the ML packages but not need GPUs, so I would propose we have two options:
- ML Notebook
- ML Notebook + GPU

There are lots of users on GCP, and it will get very expensive if they all start using GPUs!

**Comment by TomAugspurger** [comment]
Make sense. In that case, just having the ML Notebook image will get you
the environment without the GPU.
