### ISSUE TITLE
Deploy prod

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#714]
It's been a bit since we've deployed prod. This will include a few changes, including

* Updating Dask Gateway to 0.8.0
* Updating user environment images

Any objections to trying to do that today or tomorrow? What needs to be sorted out first?

- [ ] https://github.com/pangeo-data/pangeo-cloud-federation/issues/705 (?)

cc @tjcrone, @salvis2, @scottyhq

**Comment by scottyhq** [comment]
no objections. we can always move to a bigger core node on AWS if need be as part of a bump from k8s 1.16 --> 1.17.6

**Comment by tjcrone** [comment]
Ready when you are!

**Comment by salvis2** [comment]
Sounds good, just after we fix the AWS hub's CI bits: https://app.circleci.com/pipelines/github/pangeo-data/pangeo-cloud-federation/1302/workflows/a3fdba52-5681-4cb8-874a-69ff584811e7/jobs/1452

Edit: This is done!

**Comment by TomAugspurger** [comment]
Planning to deploy later today. Any objections?

**Comment by tjcrone** [comment]
Are there any blockers left on this? Thanks!

**Comment by TomAugspurger** [comment]
OK, let's try it for real now. https://github.com/pangeo-data/pangeo-cloud-federation/pull/735

**Comment by rabernat** [comment]
👍
