### ISSUE TITLE
AWS Hub not Deploying in CI

### ISSUE THREAD

**Issue by salvis2** [pangeo-data/pangeo-cloud-federation#717]
[CircleCI Build Logs](https://app.circleci.com/pipelines/github/pangeo-data/pangeo-cloud-federation/1306/workflows/3298d8b6-3dfc-42e1-ad68-a0c137f1dc4f/jobs/1456)

The error listed is: 

```
Error: UPGRADE FAILED: execution error at (pangeo-deploy/charts/daskhub/charts/jupyterhub/templates/proxy/deployment.yaml:28:32): Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!
```

@TomAugspurger , seems related to the new `daskhub` Helm chart, what does the fix need? I think that the `daskhub`'s README says the keys should still be specified in the same place, right?

**Comment by salvis2** [comment]
Oh, I think I found the issue: https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/icesat2/config/staging.yaml#L2

That line still says `pangeo` and not `daskhub`.

**Comment by TomAugspurger** [comment]
@salvis2 still seems to be failing after https://github.com/pangeo-data/pangeo-cloud-federation/pull/718.

**Comment by salvis2** [comment]
Yeah, brain fart. It's also the secrets `yaml` files; should've known since the error was talking about the `openssl` keys. I'm fixing that now.

**Comment by salvis2** [comment]
Looks good now @TomAugspurger !

**Comment by TomAugspurger** [comment]
Thanks!
