### ISSUE TITLE
OOI image not consuming environment.yml file

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo-cloud-federation#719]
The OOI image builds itself from the pangeo-notebook image, but for some reason it is not using our environment file during the image build. How can I reenable the inclusion of our environment.yml file while using this as the base image? Thanks!

**Comment by TomAugspurger** [comment]
I think that only the `base-image` is set up to check for the presence of repo2docker config files like environment.yaml. We want to ensure there's only a single `conda install` to minimize build times and image size.

So the options are to either

1. Add the necessary packages to pangeo-data/pangeo-notebook
2. Change the Dockerfile to inherit from pangeo/base-image, and update your environment.yaml file to look similar to https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/environment.yml. Notably it should include the `pangeo-notebook` conda package to ensure you get the right versions of dask, dask-gateway, and jupyterlab for our hub.

**Comment by tjcrone** [comment]
Thank you very much @TomAugspurger. Your suggested changes worked. Cheers.
