### ISSUE TITLE
Change prometheus-operator chart to kube-prometheus-stack

### ISSUE THREAD

**Issue by salvis2** [pangeo-data/pangeo-cloud-federation#732]
`prometheus-operator` is now deprecated: https://github.com/helm/charts/tree/master/stable/prometheus-operator#%EF%B8%8F--deprecated

It is now [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack). I can poke that a bit this week since I was looking into alternate storage options (mainly [Thanos](https://github.com/thanos-io/thanos), which should integrate with `kube-prometheus-stack`).

**Comment by TomAugspurger** [comment]
Both pangeo-binder and pangeo-cloud-federation are now using the individual prometheus and grafana charts.
