### ISSUE TITLE
xgcm version regression on google cluster

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo-cloud-federation#782]
I noticed yesterday together with @paigem, that in the google deployment xgcm seems to have been downgraded to v0.4.0 (both staging and production) in the google cloud (it was previously @0.5.0). 
Perhaps something happened during #776 ?

AWS has the latest version.

Could we rebuild the gc images with the newest versions (this should pick up xgcm's latest version)? 

As a side note, is there a way to check the installed versions without actually starting up a cluster? Seems like a wasteful practice to me.

**Comment by TomAugspurger** [comment]
The package versions are available somewhere in the logs at https://github.com/pangeo-data/pangeo-docker-images/actions. I agree that it'd be nice to expose them somewhere.

I don't know why it would have been downgraded. Do you know which versions of pangeo-docker-images has the right version of xgcm? Right now we're apparently on 2020.09.13: https://github.com/pangeo-data/pangeo-cloud-federation/blob/eb71da9e49d3e2a5a320cd182790d1d132e48906/deployments/gcp-uscentral1b/image/binder/Dockerfile.

https://github.com/pangeo-data/pangeo-cloud-federation/pull/780 bumps that to 2020.10.08.

**Comment by TomAugspurger** [comment]
I guess the versions are also in the condalock file. The 2020.10.08 tag does have xgcm 0.5 https://github.com/pangeo-data/pangeo-docker-images/blob/410ffb07825c00efd3a30d4fb245af845d3e510a/pangeo-notebook/conda-linux-64.lock#L423, so I'll get that deployed.

**Comment by jbusecke** [comment]
Thanks for the quick solution @TomAugspurger!

**Comment by jbusecke** [comment]
> The package versions are available somewhere in the logs at https://github.com/pangeo-data/pangeo-docker-images/actions. I agree that it'd be nice to expose them somewhere.

Could these be put into a html details style fold out the README? That would be most convenient (at least from my view).

**Comment by TomAugspurger** [comment]
> Could these be put into a html details style fold out the README? That would be most convenient (at least from my view).

I'm not sure. The README is static, but the condalock files are updated on each pull request. The image names on https://github.com/pangeo-data/pangeo-docker-images do link to the condalock files.

The latest GCP deployment should have the updated xgcm.

**Comment by jbusecke** [comment]
That is helpful, thanks.

**Comment by scottyhq** [comment]
@TomAugspurger @jbusecke  - Since https://github.com/pangeo-data/pangeo-docker-images/pull/128 simplified package lists are also in the pangeo-docker-images repository. Right now the AWS hub is setup to always pull the 'latest' image (which corresponds to most recent date tag)

For example for a given date tag:
https://github.com/pangeo-data/pangeo-docker-images/blob/2020.10.08/pangeo-notebook/packages.txt 

Difference between dates:
https://github.com/pangeo-data/pangeo-docker-images/compare/2020.10.03..2020.10.08

**Comment by jbusecke** [comment]
This is fixed now. Closing
