### ISSUE TITLE
Cloud Ops Working Group Meeting, Today (Monday Oct 12) at 11:30am EDT 

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#785]
Just a reminder that there will be a cloud ops wg meeting today at 11:30. Also listed here: http://pangeo.io/meeting-notes.html

I will chair the meeting unless someone else volunteers.

**Comment by rabernat** [comment]
https://whereby.com/pangeo

**Comment by yuvipanda** [comment]
I see notes in https://docs.google.com/document/d/1I-2VNNHoAjjeYvlCezQhFLmiu2OevqGDS5nUAP-6Hfw/edit#heading=h.lm87qluikwxu, so gonna close this issue!
