### ISSUE TITLE
ocean github auth doesn't work

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#81]
![image](https://user-images.githubusercontent.com/1197350/53194646-dc36bf80-35e1-11e9-9bbc-168048c051ee.png)

It is trying to redirect back to staging.pangeo.io

**Comment by rabernat** [comment]
This is not actually fixed

**Comment by rabernat** [comment]
I think the github oauth token has to been re-generated

**Comment by raphaeldussin** [comment]
are you still going through my OAuth app? or from a different one?
