### ISSUE TITLE
High resource usage

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#812]
@shunzlu right now you appear to be requesting many workers

```
$ kubectl -n prod get pod -l 'hub.jupyter.org/username=shunzlu' | wc -l
8766
```

That's 8766 scheduler / worker pods. At the moment, we don't have a way to limit a single user's usage, so one person can take all the resources of the entire kubernetes cluster, starving other users' resource requests.

Can you check your code to ensure you aren't using too many resources? Perhaps you're using `.adapt()` rather than `.adapt(minimum, maximum)`?

We unfortunately don't have a good way for *you* to know this on your own. There's http://grafana.us-central1-b.gcp.pangeo.io/grafana/d/a_khcwhWk2/dask-2?orgId=1&refresh=5s, but that doesn't scale well and doesn't show per-user usage yet. The proper solution is per-user limits, but that's going to take a while to implement.

**Comment by shunzi-work** [comment]
Sorry, I was using `.adapt()` instead of `.adapt(minimum, maximum)`. Now, I have stopped the code and will try to use `.adapt(minimum, maximum)` later. Thanks!

**Comment by rabernat** [comment]
Is this why the cluster was unusable this morning?

I have to say that I am confused about the recent revelation that we cannot limit each individual user's dask usage with dask gateway. I thought that was the whole point of dask gateway.

**Comment by scottyhq** [comment]
wow. i didn't realize simply using `.adapt()` could cause this. Good to know! @rabernat this has been on the books for months but no solutions yet (see https://github.com/pangeo-data/pangeo-cloud-federation/issues/693 and linked issues)

**Comment by TomAugspurger** [comment]
We can limit the size of each Dask cluster, which I think gets us most of what we want. I’ll do that later today.
