### ISSUE TITLE
Setting limits on Dask Gateway workers

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo-cloud-federation#824]
I am having some trouble setting limits on our Dask Gateway workers. I added specifications according to the [docs](https://gateway.dask.org/install-kube.html) here: https://github.com/pangeo-data/pangeo-cloud-federation/blob/41f70b4dd62304252e268766acc11309e5ed5104/deployments/ooi/config/common.yaml#L135
But now I cannot start any workers, getting the following error:
 ```[W 2020-11-03 12:54:32.713 KubeController] Failed to create pod in namespace ooi-staging - Pod "dask-worker-ae7f78abf96f428ca115bc6302a31b5d-nltzl" is invalid: spec.containers[0].resources.requests: Invalid value: "4294967296": must be less than or equal to memory limit```
So here we have a memory request for 4G even though 1.25G is supposedly specified. Any idea where this 4G is being set? Any reason why my worker requests are not working? Thanks!

**Comment by TomAugspurger** [comment]
What's the purpose of setting those limits in the `ooi` config? These are the resources requests / limits of the kubernetes pods. Our deployments expose these to users through the option handler at

https://github.com/pangeo-data/pangeo-cloud-federation/blob/41f70b4dd62304252e268766acc11309e5ed5104/pangeo-deploy/values.yaml#L93.

So I think two things are happening:

1. Your CPU core limit / request are being overridden by the user option
2. Your memory limit is being overridden by the user option, but the memory request isn't set in the option handler, so you end up with a request beyond the limit.

So the right action depends on the purpose of the limits in ooi/config/common. If you want to override the defaults, then that should go in the optionHandler. If you want to set a limit that users can't violate, that would be a limit like https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/pangeo-deploy/values.yaml#L129-L132, perhaps with a max number of workers.

**Comment by tjcrone** [comment]
The purpose is to set limits on the Dask worker cpu/memory so that I can pack a specified number in to each node. That is why I put them in dask-gateway:gateway:backend:worker. I'm not sure if I need users to be able to change this for now. But they can choose their notebook server size when they log in.

Where do your users choose their Dask worker options?

**Comment by TomAugspurger** [comment]
See options under http://pangeo.io/cloud.html#dask-gateway

**Comment by tjcrone** [comment]
Okay cool! We may want to add that to our deployment. For now though, I think I would be happy hard-coding worker cpu/memory requests and limits. I cannot find where the worker request is being set to 4G though. Is this a default upstream? I don't think I am setting this explicitly.

**Comment by TomAugspurger** [comment]
The 4G is set at
https://github.com/pangeo-data/pangeo-cloud-federation/blob/d5ceecdb9fd9f19ce88ba8bb92030d2b64ef19b8/pangeo-deploy/values.yaml#L120
.

Unfortunately, options don't compose nicely, it's all or nothing. So I
think you'd need to copy that entire

```
extraConfig:
  optionHandler: |
```

block just to override the one value.

And since you're setting these values in the helm configuration and not
exposing them to users, you're best off just excluding the worker_cores and
worker_memory options (in the Options and in the option_handler).

**Comment by tjcrone** [comment]
Oh I see. So by building out this option handler, we are obviating the simple worker requests/limits described [here](https://gateway.dask.org/install-kube.html). Hmm. I feel like this might not be ideal. Could there be a way to write the options handler so that it will still respect the options written in the yaml so that the configuration still follows the documentation?

**Comment by tjcrone** [comment]
Maybe we could change the `2` and `4` so that they revert to the values set normally if they are set.

**Comment by TomAugspurger** [comment]
I'm not sure, but possibly. You could perhaps check something like

```
if c.KubeClusterConfig.worker_memory is None:
    c.Backend.cluster_options = cluster_options
```

The idea being only provide options if the config from Helm isn't set.
Dunno if that will work or not though.

**Comment by tjcrone** [comment]
Okay. I think we should come up with something here because setting the defaults for worker cpu/memory would almost always need to be deployment-specific. Since everyone is running on different clouds with different machines in their node pools. If you have a suggestion on what might be best please let me know and I can try to implement.

**Comment by TomAugspurger** [comment]
Since GCP and AWS are fine with the settings in `values.yaml`, I think OOI
can just override with what it needs. Something like

```
daskhub:
  dask-gateway:
    gateway:
      extraConfig:
        optionHandler: |
          pass
```

**Comment by tjcrone** [comment]
Okay that seems like a reasonable way forward at this stage. Thanks I'll give it a shot.

**Comment by tjcrone** [comment]
Well, looks like `pass` will not work because something in there seems to be needed:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-d5764ac79250> in <module>
      1 # default new_cluster call
----> 2 cluster = gateway.new_cluster()

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in new_cluster(self, cluster_options, shutdown_on_close, **kwargs)
    641             cluster_options=cluster_options,
    642             shutdown_on_close=shutdown_on_close,
--> 643             **kwargs,
    644         )
    645 

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in __init__(self, address, proxy_address, public_address, auth, cluster_options, shutdown_on_close, asynchronous, loop, **kwargs)
    816             shutdown_on_close=shutdown_on_close,
    817             asynchronous=asynchronous,
--> 818             loop=loop,
    819         )
    820 

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _init_internal(self, address, proxy_address, public_address, auth, cluster_options, cluster_kwargs, shutdown_on_close, asynchronous, loop, name)
    912             self.status = "starting"
    913         if not self.asynchronous:
--> 914             self.gateway.sync(self._start_internal)
    915 
    916     @property

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    337             )
    338             try:
--> 339                 return future.result()
    340             except BaseException:
    341                 future.cancel()

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _start_internal(self)
    926             self._start_task = asyncio.ensure_future(self._start_async())
    927         try:
--> 928             await self._start_task
    929         except BaseException:
    930             # On exception, cleanup

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _start_async(self)
    940             self.status = "starting"
    941             self.name = await self.gateway._submit(
--> 942                 cluster_options=self._cluster_options, **self._cluster_kwargs
    943             )
    944         # Connect to cluster

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _submit(self, cluster_options, **kwargs)
    529             options = self._config_cluster_options()
    530             options.update(kwargs)
--> 531         resp = await self._request("POST", url, json={"cluster_options": options})
    532         data = await resp.json()
    533         return data["name"]

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _request(self, method, url, json)
    407 
    408             if resp.status in {404, 422}:
--> 409                 raise ValueError(msg)
    410             elif resp.status == 409:
    411                 raise GatewayClusterError(msg)

ValueError: Unknown fields ['image']
```

**Comment by TomAugspurger** [comment]
That may be from the singleuer.extraEnv in values.yaml

```
      extraEnv:
        # The default worker image matches the singleuser image.
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{JUPYTER_IMAGE_SPEC}'
 ```

Probably easiest to just copy that bit of the optionHandler:

```python
                  String("image", default="pangeo/pangeo-notebook:latest",
label="Image")
```

**Comment by tjcrone** [comment]
Well that's interesting. I copied the entire section and now we have this:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-d5764ac79250> in <module>
      1 # default new_cluster call
----> 2 cluster = gateway.new_cluster()

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in new_cluster(self, cluster_options, shutdown_on_close, **kwargs)
    641             cluster_options=cluster_options,
    642             shutdown_on_close=shutdown_on_close,
--> 643             **kwargs,
    644         )
    645 

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in __init__(self, address, proxy_address, public_address, auth, cluster_options, shutdown_on_close, asynchronous, loop, **kwargs)
    816             shutdown_on_close=shutdown_on_close,
    817             asynchronous=asynchronous,
--> 818             loop=loop,
    819         )
    820 

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _init_internal(self, address, proxy_address, public_address, auth, cluster_options, cluster_kwargs, shutdown_on_close, asynchronous, loop, name)
    912             self.status = "starting"
    913         if not self.asynchronous:
--> 914             self.gateway.sync(self._start_internal)
    915 
    916     @property

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    337             )
    338             try:
--> 339                 return future.result()
    340             except BaseException:
    341                 future.cancel()

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _start_internal(self)
    926             self._start_task = asyncio.ensure_future(self._start_async())
    927         try:
--> 928             await self._start_task
    929         except BaseException:
    930             # On exception, cleanup

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _start_async(self)
    940             self.status = "starting"
    941             self.name = await self.gateway._submit(
--> 942                 cluster_options=self._cluster_options, **self._cluster_kwargs
    943             )
    944         # Connect to cluster

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _submit(self, cluster_options, **kwargs)
    529             options = self._config_cluster_options()
    530             options.update(kwargs)
--> 531         resp = await self._request("POST", url, json={"cluster_options": options})
    532         data = await resp.json()
    533         return data["name"]

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _request(self, method, url, json)
    407 
    408             if resp.status in {404, 422}:
--> 409                 raise ValueError(msg)
    410             elif resp.status == 409:
    411                 raise GatewayClusterError(msg)

ValueError: 'Integer' object has no attribute 'field'
```

**Comment by TomAugspurger** [comment]
https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ooi/config/common.yaml#L161 doesn't look right. It should be a `Float` field if you're specifying the values as floats.

**Comment by TomAugspurger** [comment]
You'll also want to update https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ooi/config/common.yaml#L151, so that the `min(..., 1)` doesn't kick in.

**Comment by tjcrone** [comment]
Thanks for your help on this @TomAugspurger. I think we have the worker limits working correctly on our cluster now.
