### ISSUE TITLE
prod <- staging

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo-cloud-federation#834]
I would like to merge staging into prod (again?) because I have one straggler of a commit that I need on prod. I see that my previous PR was merged but the commit history doesn't seem to show this here? It's a little odd. Any idea what is going on? Thanks.

**Comment by TomAugspurger** [comment]
It should be in https://github.com/pangeo-data/pangeo-cloud-federation/commit/cd7a866e0c2748fd2b6bc41c3d830cc01c2df393, right?

I think I squash merged on accident.

We probably want to squash when merging to staging, and then rebase and merge when merging to prod. That will keep the git histories the cleanest.

**Comment by tjcrone** [comment]
I see. Squash merge. That makes sense I think. But when I created another prod <- staging PR, it has 42 commits which I thought were merged previously so I'm confused. And it cannot be merged automatically so something might be wrong. I would be fine if we rewrote history to fix this. I would also be fine with a merge plan that makes for a cleaner history. The prod <- staging merges get pretty ugly in the tree.

**Comment by TomAugspurger** [comment]
I'll take care of it in a bit.

**Comment by TomAugspurger** [comment]
Apologies on this. I've made a bit of a mess, but I'll get it figured out.

Long-term I think what we want is to rebase and merge to both staging on prod. Then both have a linear commit history with  the same commits.

But first we need to sync them up. I may need to do one more force push to prod to get that done.

**Comment by tjcrone** [comment]
No worries. Thanks for helping. looks to me like we are resetting from cd7a866 (dropping) to 1d11e0a and there is no rewrite on staging?

**Comment by TomAugspurger** [comment]
Right, I don't believe I touched staging at all. Right now prod and staging should be the same.

**Comment by tjcrone** [comment]
Thank you for fixing this Tom. Much appreciated.
