### ISSUE TITLE
User access to pod status

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo-cloud-federation#850]
When a user starts a Dask cluster sometimes it can take a while for workers to start, and sometimes pods run out of CPU or become orphaned when a kernel doesn't shutdown cleanly. As an admin I use kubctl *often* to understand what is going on, what pods I have running, etc., and it gives me a good view of what is actually happening. This information is not available to users but I think the user experience would be improved if this information was available to them somewhere. Does anyone know if it is possible to provide users with the ability to see the status of all the Dask Gateway pods they have started regardless of whether they have the dashboard connected to the cluster? Thanks.

**Comment by TomAugspurger** [comment]
Do you mean the scheduler and worker pods? Users can list their clusters
with `gateway.list_cluster()`, which would indicate whether the those are
still running. And they can connect to them:
https://gateway.dask.org/usage.html#connect-to-an-existing-cluster

**Comment by tjcrone** [comment]
I mean information about whether a worker pod is Running, Pending, ContainerCreating, OutofCPU, Completed, etc., for all of the pods that the user has started ever. I don't know if list_clusters() will list clusters that are orphaned (i.e. have workers but no scheduler), but sometimes it lists clusters that are Pending even though they have no workers or scheduler, and those clusters can sometimes stick around for days as far as I can tell.

I think users need a way to see the status of the pods they have started, how long since they were started, whether they are running or not, and if not why, such as because the pod is downloading its image. I don't think the Gateway object has this functionality but maybe it does and I don't know about it. Or maybe there is another tool that could provide this functionality. I think this information would not only make the user experience better but it would result in better-informed users who waste fewer resources.

**Comment by TomAugspurger** [comment]
On Thu, Nov 5, 2020 at 7:06 AM Tim Crone <notifications@github.com> wrote:

> I mean information about whether a worker pod is Running, Pending,
> ContainerCreating, OutofCPU, Completed, etc., for all of the pods that the
> user has started ever. I don't know if list_clusters() will list clusters
> that are orphaned (i.e. have workers but no scheduler),
>
That generally probably shouldn't be possible. The worker pods are
controlled by the scheduler pod, and so kubernetes should ensure that if
the scheduler pod goes away, the worker pods go away too. Though let us
know if you have examples where that's not the case (and note this is
different from the dask-scheduler *process* crashing, but the pod staying
alive, which would not clean up the worker pods. Examples of this happening
would be welcome too)

> but sometimes it lists clusters that are Pending even though they have no
> workers or scheduler, and those clusters can sometimes stick around for
> days as far as I can tell.
>
Can you clarify the state of the kubernetes clusters here? Are there
kubernetes pods with a Pending status? Presumably the autoscaler should
kick in at some point, but isn't. Looking at the events can be helpful to
debug these issues:

    kubectl -n <namespace> get events --sort-by='{.lastTimestamp}'

> I think users need a way to see the status of the pods they have started,
> how long since they were started, whether they are running or not, and if
> not why, such as because the pod is downloading its image. I don't think
> the Gateway object has this functionality but maybe it does and I don't
> know about it. Or maybe there is another tool that could provide this
> functionality. I think this information would not only make the user
> experience better but it would result in better-informed users who waste
> fewer resources.
>
Agreed that this would be useful.
https://github.com/pangeo-data/pangeo-cloud-federation/issues/768#issuecomment-702357884
has some hints on a way to do it, but requires granting user some read
access to the kubernetes API.

Eventually I suspect that dask-gateway will grow an API and possible an
HTML UI for listing this information, but it's not possible yet.

**Comment by tjcrone** [comment]
Pods go into a Pending state when there are no nodes available for them. So it's usually a temporary situation while nodes are started, but if the Kubernetes cluster is maxed out on nodes they will stay that way until other pods get shutdown. Currently users cannot know that the Kubernetes cluster is maxed out so they may wait for some very long time and have no idea why they cannot start workers.

It's worth pointing out that I'm not saying that most of these situations are problems. The issue is that users do not have any window into the status of the cluster and when things happen slowly or not at all they cannot see why. @TomAugspurger thanks for the ideas that you provided that might help alleviate this.
