### ISSUE TITLE
Squash and merge

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo-cloud-federation#881]
I'm wondering why we switched from rebase and merge to squash and merge? I thought Rebase and merge was great because the history is clean and it doesn't require a rewrite of history on my fork for every PR. I would vote to go back but perhaps there is something in our automation that won't allow this? Thanks.

**Comment by tjcrone** [comment]
Okay as @scottyhq mentioned, lots of strangeness in the history lately. I went ahead and rewrote a bit (sorry) so that prod and staging are now at b90effc. I would prefer to go back to rebase merges rather than squash merges, because the latter require forks to rewrite their history if they want to stay with upstream. Or, we can go back to regular merge commits which never caused us any problems. I'm open to whatever. Thanks everyone!

**Comment by yuvipanda** [comment]
+1 on merge commits or rebase commits :)
