### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo-cloud-federation#888]
As you all probably know, the dependabot spams forks because of a bug (https://github.com/dependabot/dependabot-core/issues/2198), which is super annoying. It might be fixed someday but I'm not sure when. I'm wondering what the dependabot is doing for us? As far as I can tell it only bumps the images on GCP and AWS, which causes build failures quite often. Is this something that we should be automating? I feel like bumping an image should be something that is done more deliberately.

**Comment by scottyhq** [comment]
> I'm wondering what the dependabot is doing for us? 

Correct, just simplifies the process of bumping the pangeo-notebook image on GCP and AWS currently. 

Agreed that the spam is annoying! And happy to turn it off and stick to manually bumping image tags

**Comment by TomAugspurger** [comment]
I'd prefer to keep it automatic.

> As far as I can tell it only bumps the images on GCP and AWS, which causes build failures quite often

Ideally these are caught as early as possible. But the only failures I've seen are for major upgrades like to the dask-gateway version. Have I missed other cases where regular updates to the packages in the notebook image have broken deployments here?

**Comment by tjcrone** [comment]
Okay sounds reasonable. I think they may fix the bug soon but we will see. @TomAugspurger I just looked back a few weeks and saw that about half of them were failing over that time period. Didn't do any deep analysis.
