### ISSUE TITLE
Unable to specify worker memory in dask gateway cluster

### ISSUE THREAD

**Issue by paigem** [pangeo-data/pangeo-cloud-federation#907]
On Pangeo Cloud (dask_gateway version 0.9.0), I am currently unable to specify the worker memory. The code I am running is reproduced below, and is the same code that I have used successfully in the past. It appears that the line specifying worker memory is doing nothing; I get the same amount of memory in my cluster whether or not I include this line (see screenshots below the code). 

```python
from dask_gateway import Gateway
from dask.distributed import Client

gateway = Gateway()
options = gateway.cluster_options()
options.worker_memory = 12
cluster = gateway.new_cluster()
cluster.scale(1)
cluster
```

I expect the above code snippet to launch a dask gateway cluster with 12 GB of memory per worker. Instead, I am getting just under 9 GB:

![Screen Shot 2021-01-07 at 16 41 10](https://user-images.githubusercontent.com/26591824/103856343-98cb9880-5108-11eb-8e57-acbd3d58fbe4.png)

I get the exact same result when I comment out the lines customizing the cluster options:
![Screen Shot 2021-01-07 at 16 44 46](https://user-images.githubusercontent.com/26591824/103856270-789bd980-5108-11eb-9b16-2613f055b60d.png)

To add to the mystery, the above code snippet yielded a `ClientResponseError` yesterday when trying to spin up a cluster, but commenting out the two "options" lines successfully started a cluster (but again with just under 9 GB of memory).

<details><summary><tt>ClientResponseError</tt></summary>
ClientResponseError                       Traceback (most recent call last)
<ipython-input-1-d39000d15581> in <module>
      3 
      4 gateway = Gateway()
----> 5 options = gateway.cluster_options()
      6 options.worker_memory=6
      7 cluster = gateway.new_cluster()

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in cluster_options(self, use_local_defaults, **kwargs)
    516             A dict of cluster options.
    517         """
--> 518         return self.sync(
    519             self._cluster_options, use_local_defaults=use_local_defaults, **kwargs
    520         )

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    341             )
    342             try:
--> 343                 return future.result()
    344             except BaseException:
    345                 future.cancel()

/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _cluster_options(self, use_local_defaults)
    495     async def _cluster_options(self, use_local_defaults=True):
    496         url = "%s/api/v1/options" % self.address
--> 497         resp = await self._request("GET", url)
    498         data = await resp.json()
    499         options = Options._from_spec(data["cluster_options"])

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _request(self, method, url, json)
    417                 raise GatewayServerError(msg)
    418             else:
--> 419                 resp.raise_for_status()
    420         else:
    421             return resp

/srv/conda/envs/notebook/lib/python3.8/site-packages/aiohttp/client_reqrep.py in raise_for_status(self)
    998             assert self.reason is not None
    999             self.release()
-> 1000             raise ClientResponseError(
   1001                 self.request_info,
   1002                 self.history,

ClientResponseError: 503, message='Service Unavailable', url=URL('http://10.39.245.173:8000/services/dask-gateway/api/v1/options')
</details>

I would appreciate any help in figuring out how to specify worker memory. Thanks!

**Comment by TomAugspurger** [comment]
Hi Paige! You had

```
options.worker_memory = 12
cluster = gateway.new_cluster()
```

Can you try with

```
options.worker_memory = 12
cluster = gateway.new_cluster(options)  # pass options here
```

I've forgotten to pass the options tons of times :/ It's really natural to forget to pass it since it's this global thing you're updating, it's natural to expect that to have an effect.

I'm not sure about the `ClientResponseError`. That indicates that the dask-gateway server had some trouble. I won't be able to look at the logs for a while (and you don't have access to them). So maybe we ignore it for now but let me know if it comes up again.

**Comment by paigem** [comment]
*face palm* Thanks @TomAugspurger! It works now. This was indeed just a silly typo on my part.

It is still mysterious that it returned a `ClientRresponseError` each time I tried to start a cluster the previous day. I admit that I often seem to run into transient errors like this when using dask where it errors one day and works fine the next. Anyway, happy to close this for now and will report back if I get any more such errors!
