### ISSUE TITLE
Tab autocomplete not working

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo-cloud-federation#923]
I noticed that tab autocomplete is not working in the cloud deployment. This is quite annoying, but like a major problem. I had recently experienced the same problem on my personal computer, and the following solution fixed it for me: 

> I recently upgraded all my packages and autocomplete using tab just stopped working. This has happened to me a few times on different environments and machines, and not sure if it is the same problem everytime (but the level of annoyance is the same). But finally a solution worked for one case. Seems like usually the problem comes from a package called jedi, and for some reason the latest version of this package has the problem but not older versions (https://github.com/jupyter/notebook/issues/2435 scroll to bottom). So downgrading solved the issue for me this time (
`pip install jedi==0.17.2`)

**Comment by rabernat** [comment]
Thanks for this report @dhruvbalwada! Perhaps the way to get this fixed is to pin jedi over in https://github.com/pangeo-data/pangeo-docker-images/

**Comment by scottyhq** [comment]
seems to be working on the master image, so things will be fixed starting with pangeo/pangeo-notebook:2021.02.02

<img width="686" alt="Screen Shot 2021-02-02 at 12 26 40 PM" src="https://user-images.githubusercontent.com/3924836/106658333-ff9a7100-6551-11eb-86bb-e2ec5f7345c2.png">

**Comment by rabernat** [comment]
Thanks so much for checking on this Scott!

**Comment by scottyhq** [comment]
closed by #927
