### ISSUE TITLE
ocean docker images are not getting pushed

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#98]
Hubploy is not pushing my notebook docker images. Consequently, I am getting errors in my hub like:
```
Failed to pull image "us.gcr.io/pangeo-181919/ocean-pangeo-io-notebook:f1112be": rpc error: code = Unknown desc = Error response from daemon: manifest for us.gcr.io/pangeo-181919/ocean-pangeo-io-notebook:f1112be not found
```

It seems like the commit `f1112be` is getting [built](https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/186) on the PR branch (#97), but, on the [deploy job](https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/187), it determines nothing needs to be done.
```
#!/bin/bash -eo pipefail
hubploy build ocean --commit-range ${COMMIT_RANGE} --push
Activated service account credentials for: [hubploy-circleci@pangeo-181919.iam.gserviceaccount.com]
WARNING: `docker` not in system PATH.
`docker` and `docker-credential-gcloud` need to be in the same PATH in order to work correctly together.
gcloud's Docker credential helper can be configured but it will not work until this is corrected.
gcloud credential helpers already registered correctly.
Image us.gcr.io/pangeo-181919/ocean-pangeo-io-notebook:f1112be: already up to date
```

As a result, the image is never pushed.

Relevant circleci config is here:
https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/.circleci/config.yml#L125-L129

**Comment by rabernat** [comment]
#103 was from my fork and it still didn't push properly on merge.

**Comment by rabernat** [comment]
So I think the problem is that `COMMIT_RANGE` is being set wrong in the deploy builds. Below is the output of the following section of the circleci job:

https://github.com/pangeo-data/pangeo-cloud-federation/blob/635889cee5d87818df99d46f48f7191e14682610/.circleci/config.yml#L104-L110

```
#!/bin/bash -eo pipefail
# CircleCI doesn't have equivalent to Travis' COMMIT_RANGE
COMMIT_RANGE=$(./.circleci/get-commit-range.py)
echo ${COMMIT_RANGE}
echo "export COMMIT_RANGE='${COMMIT_RANGE}'" >> ${BASH_ENV}
dcc1c71536d5a59f0af589190e4a3868b98aa225...327e7f6b4b9a4221ba690ad8c9bb7e2c24bbc962
```

This output is the same on _every single build on the staging branch_. It corresponds to a merge from Feb. 13. From `git log`:
```
commit 28350f08fd34e67513887ea6a1debca87d2d66fc
Merge: dcc1c71 327e7f6
Author: raphael dussin <raphael.dussin@gmail.com>
Date:   Wed Feb 13 15:07:05 2019 -0500

    Merge pull request #53 from raphaeldussin/staging
    
    add seawater pkg
```

So it seems like our problem may be with the `get-commit-range.py` script.

**Comment by rabernat** [comment]
The problem is definitely these lines:

https://github.com/pangeo-data/pangeo-cloud-federation/blob/635889cee5d87818df99d46f48f7191e14682610/.circleci/get-commit-range.py#L24-L27

There are many prs for whom `pr.head.ref == 'staging'`. It just returns the first one.

**Comment by yuvipanda** [comment]
@rabernat I've implemented a different, more robust way to check when images need to be rebuilt that can be used during deployment. The commit messages in https://github.com/yuvipanda/hubploy/commit/8705e58f46622d6ede96029da81c09fd807fdd36 has rationale.

You can see the changes needed to the repo in https://github.com/berkeley-dsep-infra/datahub/compare/49b8e77894cbe26c523452982004fba3e2590552...c0f099024d32d74ba4b3d9bd3204e3d151d5741c They should translate pretty directly here.

**Comment by yuvipanda** [comment]
I'm not going to make the changes here since I think it conflicts with @jhamman (and others'?) experiments with AWS on hubploy.

**Comment by jhamman** [comment]
Thanks @yuvipanda - I've merged your changes into the aws hubploy branch so they are active here.

**Comment by rabernat** [comment]
> I've merged your changes into the aws hubploy branch so they are active here.

Where is this?

**Comment by rabernat** [comment]
n.m. found it: https://github.com/jhamman/hubploy/commit/fc55116ede59723a26f18ffcb7bb48e29497ac82

**Comment by rabernat** [comment]
I'm pretty sure all the lines after `pip install` in the "install dependencies" step are not getting run

https://github.com/pangeo-data/pangeo-cloud-federation/blob/7def782096362fc0ba7f355bb82fa3ba5f5bdd6d/.circleci/config.yml#L84-L96
