### ISSUE TITLE
`finalize_target` is slow on large recipes with remote filesystem

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#987]
`finalize_target`, specifically https://github.com/pangeo-forge/pangeo-forge-recipes/blob/4f8c0522c1395aaf15a820cfd637a1f1e76729b2/pangeo_forge_recipes/recipes/xarray_zarr.py#L558, can be slow.

We call `set(group)` to figure out what which variables are available. I didn't realize it, but apparently that can trigger a full listing of the bucket / storage container, which is slow with many objects. (Zarr has a fastpath if the object implements `listdirs` https://github.com/zarr-developers/zarr-python/blob/f0677c2e051cad672e781c6bf63b5edfe57aaca4/zarr/storage.py#L163-L165), but fsspec mappers don't; The Azure portal does it somehow, so it might be feasible)

I wonder if we can determine the set of variables based on some other mechanism. For now, I'm going to manually run `finalize_target` with hard-coded variables for the dataset I'm working on (gpm-imerg).

cc @sharkinsspatial, I think that this is one of the reasons `finalize_target` was taking so long for you.

edit: Oh I just discoved the `walk_blobs` method in azure.storage.blob. Perahps fsspec could use `walk` to implement `listdirs`. I'll investigate and open an fsspec issue if it seems promising.

**Comment by rabernat** [comment]
Thanks for reporting Tom.

This seems like something that we should try to fix upstream, in fsspec and / or the fsspec + Zarr interface.

In the meantime, if listing the `group` is really slow, we could at least only do it once. I think the current code iterates through the group keys twice.

**Comment by rabernat** [comment]
This probably should be a pangeo-forge-recipes issue?

**Comment by TomAugspurger** [comment]
Ohhh whoops. Yes. wrong repo. I'll move it.
